package client







































































































}	return nil	}		return c.conn.Close()	if c.conn != nil {func (c *BankingGRPCClient) Close() error {// Close closes the gRPC connection}	return resp, nil	}		return nil, fmt.Errorf("failed to verify bank account: %w", err)	if err != nil {	resp, err := c.client.VerifyBankAccount(ctx, req)	}		BankId:        bankID,		AccountNumber: accountNumber,	req := &pb.VerifyBankAccountRequest{func (c *BankingGRPCClient) VerifyBankAccount(ctx context.Context, accountNumber string, bankID uint32) (*pb.VerifyBankAccountResponse, error) {// VerifyBankAccount verifies if a bank account is valid}	return resp, nil	}		return nil, fmt.Errorf("failed to upsert bank details: %w", err)	if err != nil {	resp, err := c.client.UpsertBankDetails(ctx, req)	}		AccountHolderName: accountHolderName,		AccountNumber:     accountNumber,		BankId:            bankID,		StudentId:         studentID,	req := &pb.UpsertBankDetailsRequest{func (c *BankingGRPCClient) UpsertBankDetails(ctx context.Context, studentID, bankID uint32, accountNumber, accountHolderName string) (*pb.BankDetailsResponse, error) {// UpsertBankDetails creates or updates bank details for a student}	return resp, nil	}		return nil, fmt.Errorf("failed to get student bank details: %w", err)	if err != nil {	resp, err := c.client.GetStudentBankDetails(ctx, req)	}		StudentId: studentID,	req := &pb.GetBankDetailsRequest{func (c *BankingGRPCClient) GetStudentBankDetails(ctx context.Context, studentID uint32) (*pb.BankDetailsResponse, error) {// GetStudentBankDetails retrieves bank details for a student}	}, nil		client: pb.NewBankingServiceClient(conn),		conn:   conn,	return &BankingGRPCClient{	log.Printf("Connected to Banking Service gRPC at %s", address)	}		return nil, fmt.Errorf("failed to connect to banking service at %s: %w", address, err)	if err != nil {	)		grpc.WithBlock(),		grpc.WithTransportCredentials(insecure.NewCredentials()),		address,		ctx,	conn, err := grpc.DialContext(	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	// Create gRPC connection with timeout	}		address = "localhost:50053" // Default for local development	if address == "" {	address := os.Getenv("BANKING_GRPC_URL")	// Get Banking Service gRPC address from environmentfunc NewBankingGRPCClient() (*BankingGRPCClient, error) {// NewBankingGRPCClient creates a new Banking Service gRPC client}	client pb.BankingServiceClient	conn   *grpc.ClientConntype BankingGRPCClient struct {// BankingGRPCClient handles gRPC communication with Banking Service)	"google.golang.org/grpc/credentials/insecure"	"google.golang.org/grpc"	pb "student_management_service/pb/banking"	"time"	"os"	"log"	"fmt"	"context"import (