// proto/banking/banking.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/banking/banking.proto

package banking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank) Reset() {
	*x = Bank{}
	mi := &file_proto_banking_banking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{0}
}

func (x *Bank) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bank) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bank) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type StudentBankDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId         string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	BankId            string                 `protobuf:"bytes,3,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolderName string                 `protobuf:"bytes,5,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	Bank              *Bank                  `protobuf:"bytes,8,opt,name=bank,proto3" json:"bank,omitempty"` // populated bank details
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StudentBankDetails) Reset() {
	*x = StudentBankDetails{}
	mi := &file_proto_banking_banking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentBankDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentBankDetails) ProtoMessage() {}

func (x *StudentBankDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentBankDetails.ProtoReflect.Descriptor instead.
func (*StudentBankDetails) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{1}
}

func (x *StudentBankDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudentBankDetails) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentBankDetails) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *StudentBankDetails) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *StudentBankDetails) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

func (x *StudentBankDetails) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StudentBankDetails) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *StudentBankDetails) GetBank() *Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

// Bank operations
type GetBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankRequest) Reset() {
	*x = GetBankRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankRequest) ProtoMessage() {}

func (x *GetBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankRequest.ProtoReflect.Descriptor instead.
func (*GetBankRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{2}
}

func (x *GetBankRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bank          *Bank                  `protobuf:"bytes,1,opt,name=bank,proto3" json:"bank,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankResponse) Reset() {
	*x = GetBankResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankResponse) ProtoMessage() {}

func (x *GetBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankResponse.ProtoReflect.Descriptor instead.
func (*GetBankResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{3}
}

func (x *GetBankResponse) GetBank() *Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *GetBankResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListBanksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBanksRequest) Reset() {
	*x = ListBanksRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBanksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBanksRequest) ProtoMessage() {}

func (x *ListBanksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBanksRequest.ProtoReflect.Descriptor instead.
func (*ListBanksRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{4}
}

func (x *ListBanksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBanksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBanksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banks         []*Bank                `protobuf:"bytes,1,rep,name=banks,proto3" json:"banks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBanksResponse) Reset() {
	*x = ListBanksResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBanksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBanksResponse) ProtoMessage() {}

func (x *ListBanksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBanksResponse.ProtoReflect.Descriptor instead.
func (*ListBanksResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{5}
}

func (x *ListBanksResponse) GetBanks() []*Bank {
	if x != nil {
		return x.Banks
	}
	return nil
}

func (x *ListBanksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBanksResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankRequest) Reset() {
	*x = CreateBankRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankRequest) ProtoMessage() {}

func (x *CreateBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankRequest.ProtoReflect.Descriptor instead.
func (*CreateBankRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBankRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bank          *Bank                  `protobuf:"bytes,1,opt,name=bank,proto3" json:"bank,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankResponse) Reset() {
	*x = CreateBankResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankResponse) ProtoMessage() {}

func (x *CreateBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankResponse.ProtoReflect.Descriptor instead.
func (*CreateBankResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBankResponse) GetBank() *Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *CreateBankResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBankRequest) Reset() {
	*x = UpdateBankRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBankRequest) ProtoMessage() {}

func (x *UpdateBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBankRequest.ProtoReflect.Descriptor instead.
func (*UpdateBankRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBankRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBankRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bank          *Bank                  `protobuf:"bytes,1,opt,name=bank,proto3" json:"bank,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBankResponse) Reset() {
	*x = UpdateBankResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBankResponse) ProtoMessage() {}

func (x *UpdateBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBankResponse.ProtoReflect.Descriptor instead.
func (*UpdateBankResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBankResponse) GetBank() *Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *UpdateBankResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBankRequest) Reset() {
	*x = DeleteBankRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBankRequest) ProtoMessage() {}

func (x *DeleteBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBankRequest.ProtoReflect.Descriptor instead.
func (*DeleteBankRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBankRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBankResponse) Reset() {
	*x = DeleteBankResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBankResponse) ProtoMessage() {}

func (x *DeleteBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBankResponse.ProtoReflect.Descriptor instead.
func (*DeleteBankResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBankResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBankResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Student Bank Details operations
type GetStudentBankDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentBankDetailsRequest) Reset() {
	*x = GetStudentBankDetailsRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentBankDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentBankDetailsRequest) ProtoMessage() {}

func (x *GetStudentBankDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentBankDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetStudentBankDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{12}
}

func (x *GetStudentBankDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStudentBankDetailsByStudentIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentBankDetailsByStudentIdRequest) Reset() {
	*x = GetStudentBankDetailsByStudentIdRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentBankDetailsByStudentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentBankDetailsByStudentIdRequest) ProtoMessage() {}

func (x *GetStudentBankDetailsByStudentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentBankDetailsByStudentIdRequest.ProtoReflect.Descriptor instead.
func (*GetStudentBankDetailsByStudentIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{13}
}

func (x *GetStudentBankDetailsByStudentIdRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetStudentBankDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *StudentBankDetails    `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentBankDetailsResponse) Reset() {
	*x = GetStudentBankDetailsResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentBankDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentBankDetailsResponse) ProtoMessage() {}

func (x *GetStudentBankDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentBankDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetStudentBankDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{14}
}

func (x *GetStudentBankDetailsResponse) GetDetails() *StudentBankDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *GetStudentBankDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateStudentBankDetailsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StudentId         string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	BankId            string                 `protobuf:"bytes,2,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolderName string                 `protobuf:"bytes,4,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateStudentBankDetailsRequest) Reset() {
	*x = CreateStudentBankDetailsRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentBankDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentBankDetailsRequest) ProtoMessage() {}

func (x *CreateStudentBankDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentBankDetailsRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentBankDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{15}
}

func (x *CreateStudentBankDetailsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateStudentBankDetailsRequest) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *CreateStudentBankDetailsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateStudentBankDetailsRequest) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

type CreateStudentBankDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *StudentBankDetails    `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentBankDetailsResponse) Reset() {
	*x = CreateStudentBankDetailsResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentBankDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentBankDetailsResponse) ProtoMessage() {}

func (x *CreateStudentBankDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentBankDetailsResponse.ProtoReflect.Descriptor instead.
func (*CreateStudentBankDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{16}
}

func (x *CreateStudentBankDetailsResponse) GetDetails() *StudentBankDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CreateStudentBankDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateStudentBankDetailsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId         string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	BankId            string                 `protobuf:"bytes,3,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolderName string                 `protobuf:"bytes,5,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateStudentBankDetailsRequest) Reset() {
	*x = UpdateStudentBankDetailsRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentBankDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentBankDetailsRequest) ProtoMessage() {}

func (x *UpdateStudentBankDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentBankDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentBankDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateStudentBankDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStudentBankDetailsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *UpdateStudentBankDetailsRequest) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *UpdateStudentBankDetailsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UpdateStudentBankDetailsRequest) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

type UpdateStudentBankDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *StudentBankDetails    `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentBankDetailsResponse) Reset() {
	*x = UpdateStudentBankDetailsResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentBankDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentBankDetailsResponse) ProtoMessage() {}

func (x *UpdateStudentBankDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentBankDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateStudentBankDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStudentBankDetailsResponse) GetDetails() *StudentBankDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *UpdateStudentBankDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteStudentBankDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentBankDetailsRequest) Reset() {
	*x = DeleteStudentBankDetailsRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentBankDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentBankDetailsRequest) ProtoMessage() {}

func (x *DeleteStudentBankDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentBankDetailsRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentBankDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteStudentBankDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteStudentBankDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentBankDetailsResponse) Reset() {
	*x = DeleteStudentBankDetailsResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentBankDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentBankDetailsResponse) ProtoMessage() {}

func (x *DeleteStudentBankDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentBankDetailsResponse.ProtoReflect.Descriptor instead.
func (*DeleteStudentBankDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteStudentBankDetailsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteStudentBankDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Bulk operations
type GetStudentsBankDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentIds    []string               `protobuf:"bytes,1,rep,name=student_ids,json=studentIds,proto3" json:"student_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentsBankDetailsRequest) Reset() {
	*x = GetStudentsBankDetailsRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentsBankDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsBankDetailsRequest) ProtoMessage() {}

func (x *GetStudentsBankDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsBankDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetStudentsBankDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{21}
}

func (x *GetStudentsBankDetailsRequest) GetStudentIds() []string {
	if x != nil {
		return x.StudentIds
	}
	return nil
}

type GetStudentsBankDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       []*StudentBankDetails  `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentsBankDetailsResponse) Reset() {
	*x = GetStudentsBankDetailsResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentsBankDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsBankDetailsResponse) ProtoMessage() {}

func (x *GetStudentsBankDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsBankDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetStudentsBankDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{22}
}

func (x *GetStudentsBankDetailsResponse) GetDetails() []*StudentBankDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *GetStudentsBankDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ValidateBankAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBankAccountRequest) Reset() {
	*x = ValidateBankAccountRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBankAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBankAccountRequest) ProtoMessage() {}

func (x *ValidateBankAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBankAccountRequest.ProtoReflect.Descriptor instead.
func (*ValidateBankAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{23}
}

func (x *ValidateBankAccountRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ValidateBankAccountRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type ValidateBankAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Details       *StudentBankDetails    `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBankAccountResponse) Reset() {
	*x = ValidateBankAccountResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBankAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBankAccountResponse) ProtoMessage() {}

func (x *ValidateBankAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBankAccountResponse.ProtoReflect.Descriptor instead.
func (*ValidateBankAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{24}
}

func (x *ValidateBankAccountResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateBankAccountResponse) GetDetails() *StudentBankDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ValidateBankAccountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_banking_banking_proto protoreflect.FileDescriptor

const file_proto_banking_banking_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/banking/banking.proto\x12\abanking\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x04Bank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\"\xce\x02\n" +
	"\x12StudentBankDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x17\n" +
	"\abank_id\x18\x03 \x01(\tR\x06bankId\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12.\n" +
	"\x13account_holder_name\x18\x05 \x01(\tR\x11accountHolderName\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12!\n" +
	"\x04bank\x18\b \x01(\v2\r.banking.BankR\x04bank\" \n" +
	"\x0eGetBankRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x0fGetBankResponse\x12!\n" +
	"\x04bank\x18\x01 \x01(\v2\r.banking.BankR\x04bank\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"C\n" +
	"\x10ListBanksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"d\n" +
	"\x11ListBanksResponse\x12#\n" +
	"\x05banks\x18\x01 \x03(\v2\r.banking.BankR\x05banks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"'\n" +
	"\x11CreateBankRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\x12CreateBankResponse\x12!\n" +
	"\x04bank\x18\x01 \x01(\v2\r.banking.BankR\x04bank\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\x11UpdateBankRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"M\n" +
	"\x12UpdateBankResponse\x12!\n" +
	"\x04bank\x18\x01 \x01(\v2\r.banking.BankR\x04bank\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"#\n" +
	"\x11DeleteBankRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x12DeleteBankResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\x1cGetStudentBankDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"'GetStudentBankDetailsByStudentIdRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"l\n" +
	"\x1dGetStudentBankDetailsResponse\x125\n" +
	"\adetails\x18\x01 \x01(\v2\x1b.banking.StudentBankDetailsR\adetails\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb0\x01\n" +
	"\x1fCreateStudentBankDetailsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x17\n" +
	"\abank_id\x18\x02 \x01(\tR\x06bankId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12.\n" +
	"\x13account_holder_name\x18\x04 \x01(\tR\x11accountHolderName\"o\n" +
	" CreateStudentBankDetailsResponse\x125\n" +
	"\adetails\x18\x01 \x01(\v2\x1b.banking.StudentBankDetailsR\adetails\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc0\x01\n" +
	"\x1fUpdateStudentBankDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x17\n" +
	"\abank_id\x18\x03 \x01(\tR\x06bankId\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12.\n" +
	"\x13account_holder_name\x18\x05 \x01(\tR\x11accountHolderName\"o\n" +
	" UpdateStudentBankDetailsResponse\x125\n" +
	"\adetails\x18\x01 \x01(\v2\x1b.banking.StudentBankDetailsR\adetails\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\x1fDeleteStudentBankDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	" DeleteStudentBankDetailsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x1dGetStudentsBankDetailsRequest\x12\x1f\n" +
	"\vstudent_ids\x18\x01 \x03(\tR\n" +
	"studentIds\"m\n" +
	"\x1eGetStudentsBankDetailsResponse\x125\n" +
	"\adetails\x18\x01 \x03(\v2\x1b.banking.StudentBankDetailsR\adetails\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"b\n" +
	"\x1aValidateBankAccountRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\"\x85\x01\n" +
	"\x1bValidateBankAccountResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x125\n" +
	"\adetails\x18\x02 \x01(\v2\x1b.banking.StudentBankDetailsR\adetails\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xed\b\n" +
	"\x0eBankingService\x12<\n" +
	"\aGetBank\x12\x17.banking.GetBankRequest\x1a\x18.banking.GetBankResponse\x12B\n" +
	"\tListBanks\x12\x19.banking.ListBanksRequest\x1a\x1a.banking.ListBanksResponse\x12E\n" +
	"\n" +
	"CreateBank\x12\x1a.banking.CreateBankRequest\x1a\x1b.banking.CreateBankResponse\x12E\n" +
	"\n" +
	"UpdateBank\x12\x1a.banking.UpdateBankRequest\x1a\x1b.banking.UpdateBankResponse\x12E\n" +
	"\n" +
	"DeleteBank\x12\x1a.banking.DeleteBankRequest\x1a\x1b.banking.DeleteBankResponse\x12f\n" +
	"\x15GetStudentBankDetails\x12%.banking.GetStudentBankDetailsRequest\x1a&.banking.GetStudentBankDetailsResponse\x12|\n" +
	" GetStudentBankDetailsByStudentId\x120.banking.GetStudentBankDetailsByStudentIdRequest\x1a&.banking.GetStudentBankDetailsResponse\x12o\n" +
	"\x18CreateStudentBankDetails\x12(.banking.CreateStudentBankDetailsRequest\x1a).banking.CreateStudentBankDetailsResponse\x12o\n" +
	"\x18UpdateStudentBankDetails\x12(.banking.UpdateStudentBankDetailsRequest\x1a).banking.UpdateStudentBankDetailsResponse\x12o\n" +
	"\x18DeleteStudentBankDetails\x12(.banking.DeleteStudentBankDetailsRequest\x1a).banking.DeleteStudentBankDetailsResponse\x12i\n" +
	"\x16GetStudentsBankDetails\x12&.banking.GetStudentsBankDetailsRequest\x1a'.banking.GetStudentsBankDetailsResponse\x12`\n" +
	"\x13ValidateBankAccount\x12#.banking.ValidateBankAccountRequest\x1a$.banking.ValidateBankAccountResponseB:Z8github.com/yourusername/rub-student-portal/proto/bankingb\x06proto3"

var (
	file_proto_banking_banking_proto_rawDescOnce sync.Once
	file_proto_banking_banking_proto_rawDescData []byte
)

func file_proto_banking_banking_proto_rawDescGZIP() []byte {
	file_proto_banking_banking_proto_rawDescOnce.Do(func() {
		file_proto_banking_banking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_banking_banking_proto_rawDesc), len(file_proto_banking_banking_proto_rawDesc)))
	})
	return file_proto_banking_banking_proto_rawDescData
}

var file_proto_banking_banking_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_banking_banking_proto_goTypes = []any{
	(*Bank)(nil),                                    // 0: banking.Bank
	(*StudentBankDetails)(nil),                      // 1: banking.StudentBankDetails
	(*GetBankRequest)(nil),                          // 2: banking.GetBankRequest
	(*GetBankResponse)(nil),                         // 3: banking.GetBankResponse
	(*ListBanksRequest)(nil),                        // 4: banking.ListBanksRequest
	(*ListBanksResponse)(nil),                       // 5: banking.ListBanksResponse
	(*CreateBankRequest)(nil),                       // 6: banking.CreateBankRequest
	(*CreateBankResponse)(nil),                      // 7: banking.CreateBankResponse
	(*UpdateBankRequest)(nil),                       // 8: banking.UpdateBankRequest
	(*UpdateBankResponse)(nil),                      // 9: banking.UpdateBankResponse
	(*DeleteBankRequest)(nil),                       // 10: banking.DeleteBankRequest
	(*DeleteBankResponse)(nil),                      // 11: banking.DeleteBankResponse
	(*GetStudentBankDetailsRequest)(nil),            // 12: banking.GetStudentBankDetailsRequest
	(*GetStudentBankDetailsByStudentIdRequest)(nil), // 13: banking.GetStudentBankDetailsByStudentIdRequest
	(*GetStudentBankDetailsResponse)(nil),           // 14: banking.GetStudentBankDetailsResponse
	(*CreateStudentBankDetailsRequest)(nil),         // 15: banking.CreateStudentBankDetailsRequest
	(*CreateStudentBankDetailsResponse)(nil),        // 16: banking.CreateStudentBankDetailsResponse
	(*UpdateStudentBankDetailsRequest)(nil),         // 17: banking.UpdateStudentBankDetailsRequest
	(*UpdateStudentBankDetailsResponse)(nil),        // 18: banking.UpdateStudentBankDetailsResponse
	(*DeleteStudentBankDetailsRequest)(nil),         // 19: banking.DeleteStudentBankDetailsRequest
	(*DeleteStudentBankDetailsResponse)(nil),        // 20: banking.DeleteStudentBankDetailsResponse
	(*GetStudentsBankDetailsRequest)(nil),           // 21: banking.GetStudentsBankDetailsRequest
	(*GetStudentsBankDetailsResponse)(nil),          // 22: banking.GetStudentsBankDetailsResponse
	(*ValidateBankAccountRequest)(nil),              // 23: banking.ValidateBankAccountRequest
	(*ValidateBankAccountResponse)(nil),             // 24: banking.ValidateBankAccountResponse
	(*timestamppb.Timestamp)(nil),                   // 25: google.protobuf.Timestamp
}
var file_proto_banking_banking_proto_depIdxs = []int32{
	25, // 0: banking.Bank.created_at:type_name -> google.protobuf.Timestamp
	25, // 1: banking.Bank.modified_at:type_name -> google.protobuf.Timestamp
	25, // 2: banking.StudentBankDetails.created_at:type_name -> google.protobuf.Timestamp
	25, // 3: banking.StudentBankDetails.modified_at:type_name -> google.protobuf.Timestamp
	0,  // 4: banking.StudentBankDetails.bank:type_name -> banking.Bank
	0,  // 5: banking.GetBankResponse.bank:type_name -> banking.Bank
	0,  // 6: banking.ListBanksResponse.banks:type_name -> banking.Bank
	0,  // 7: banking.CreateBankResponse.bank:type_name -> banking.Bank
	0,  // 8: banking.UpdateBankResponse.bank:type_name -> banking.Bank
	1,  // 9: banking.GetStudentBankDetailsResponse.details:type_name -> banking.StudentBankDetails
	1,  // 10: banking.CreateStudentBankDetailsResponse.details:type_name -> banking.StudentBankDetails
	1,  // 11: banking.UpdateStudentBankDetailsResponse.details:type_name -> banking.StudentBankDetails
	1,  // 12: banking.GetStudentsBankDetailsResponse.details:type_name -> banking.StudentBankDetails
	1,  // 13: banking.ValidateBankAccountResponse.details:type_name -> banking.StudentBankDetails
	2,  // 14: banking.BankingService.GetBank:input_type -> banking.GetBankRequest
	4,  // 15: banking.BankingService.ListBanks:input_type -> banking.ListBanksRequest
	6,  // 16: banking.BankingService.CreateBank:input_type -> banking.CreateBankRequest
	8,  // 17: banking.BankingService.UpdateBank:input_type -> banking.UpdateBankRequest
	10, // 18: banking.BankingService.DeleteBank:input_type -> banking.DeleteBankRequest
	12, // 19: banking.BankingService.GetStudentBankDetails:input_type -> banking.GetStudentBankDetailsRequest
	13, // 20: banking.BankingService.GetStudentBankDetailsByStudentId:input_type -> banking.GetStudentBankDetailsByStudentIdRequest
	15, // 21: banking.BankingService.CreateStudentBankDetails:input_type -> banking.CreateStudentBankDetailsRequest
	17, // 22: banking.BankingService.UpdateStudentBankDetails:input_type -> banking.UpdateStudentBankDetailsRequest
	19, // 23: banking.BankingService.DeleteStudentBankDetails:input_type -> banking.DeleteStudentBankDetailsRequest
	21, // 24: banking.BankingService.GetStudentsBankDetails:input_type -> banking.GetStudentsBankDetailsRequest
	23, // 25: banking.BankingService.ValidateBankAccount:input_type -> banking.ValidateBankAccountRequest
	3,  // 26: banking.BankingService.GetBank:output_type -> banking.GetBankResponse
	5,  // 27: banking.BankingService.ListBanks:output_type -> banking.ListBanksResponse
	7,  // 28: banking.BankingService.CreateBank:output_type -> banking.CreateBankResponse
	9,  // 29: banking.BankingService.UpdateBank:output_type -> banking.UpdateBankResponse
	11, // 30: banking.BankingService.DeleteBank:output_type -> banking.DeleteBankResponse
	14, // 31: banking.BankingService.GetStudentBankDetails:output_type -> banking.GetStudentBankDetailsResponse
	14, // 32: banking.BankingService.GetStudentBankDetailsByStudentId:output_type -> banking.GetStudentBankDetailsResponse
	16, // 33: banking.BankingService.CreateStudentBankDetails:output_type -> banking.CreateStudentBankDetailsResponse
	18, // 34: banking.BankingService.UpdateStudentBankDetails:output_type -> banking.UpdateStudentBankDetailsResponse
	20, // 35: banking.BankingService.DeleteStudentBankDetails:output_type -> banking.DeleteStudentBankDetailsResponse
	22, // 36: banking.BankingService.GetStudentsBankDetails:output_type -> banking.GetStudentsBankDetailsResponse
	24, // 37: banking.BankingService.ValidateBankAccount:output_type -> banking.ValidateBankAccountResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_banking_banking_proto_init() }
func file_proto_banking_banking_proto_init() {
	if File_proto_banking_banking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_banking_banking_proto_rawDesc), len(file_proto_banking_banking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_banking_banking_proto_goTypes,
		DependencyIndexes: file_proto_banking_banking_proto_depIdxs,
		MessageInfos:      file_proto_banking_banking_proto_msgTypes,
	}.Build()
	File_proto_banking_banking_proto = out.File
	file_proto_banking_banking_proto_goTypes = nil
	file_proto_banking_banking_proto_depIdxs = nil
}
