// proto/banking/banking.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/banking/banking.proto

package banking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankingService_GetBank_FullMethodName                          = "/banking.BankingService/GetBank"
	BankingService_ListBanks_FullMethodName                        = "/banking.BankingService/ListBanks"
	BankingService_CreateBank_FullMethodName                       = "/banking.BankingService/CreateBank"
	BankingService_UpdateBank_FullMethodName                       = "/banking.BankingService/UpdateBank"
	BankingService_DeleteBank_FullMethodName                       = "/banking.BankingService/DeleteBank"
	BankingService_GetStudentBankDetails_FullMethodName            = "/banking.BankingService/GetStudentBankDetails"
	BankingService_GetStudentBankDetailsByStudentId_FullMethodName = "/banking.BankingService/GetStudentBankDetailsByStudentId"
	BankingService_CreateStudentBankDetails_FullMethodName         = "/banking.BankingService/CreateStudentBankDetails"
	BankingService_UpdateStudentBankDetails_FullMethodName         = "/banking.BankingService/UpdateStudentBankDetails"
	BankingService_DeleteStudentBankDetails_FullMethodName         = "/banking.BankingService/DeleteStudentBankDetails"
	BankingService_GetStudentsBankDetails_FullMethodName           = "/banking.BankingService/GetStudentsBankDetails"
	BankingService_ValidateBankAccount_FullMethodName              = "/banking.BankingService/ValidateBankAccount"
)

// BankingServiceClient is the client API for BankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankingServiceClient interface {
	// Bank CRUD operations
	GetBank(ctx context.Context, in *GetBankRequest, opts ...grpc.CallOption) (*GetBankResponse, error)
	ListBanks(ctx context.Context, in *ListBanksRequest, opts ...grpc.CallOption) (*ListBanksResponse, error)
	CreateBank(ctx context.Context, in *CreateBankRequest, opts ...grpc.CallOption) (*CreateBankResponse, error)
	UpdateBank(ctx context.Context, in *UpdateBankRequest, opts ...grpc.CallOption) (*UpdateBankResponse, error)
	DeleteBank(ctx context.Context, in *DeleteBankRequest, opts ...grpc.CallOption) (*DeleteBankResponse, error)
	// Student Bank Details operations
	GetStudentBankDetails(ctx context.Context, in *GetStudentBankDetailsRequest, opts ...grpc.CallOption) (*GetStudentBankDetailsResponse, error)
	GetStudentBankDetailsByStudentId(ctx context.Context, in *GetStudentBankDetailsByStudentIdRequest, opts ...grpc.CallOption) (*GetStudentBankDetailsResponse, error)
	CreateStudentBankDetails(ctx context.Context, in *CreateStudentBankDetailsRequest, opts ...grpc.CallOption) (*CreateStudentBankDetailsResponse, error)
	UpdateStudentBankDetails(ctx context.Context, in *UpdateStudentBankDetailsRequest, opts ...grpc.CallOption) (*UpdateStudentBankDetailsResponse, error)
	DeleteStudentBankDetails(ctx context.Context, in *DeleteStudentBankDetailsRequest, opts ...grpc.CallOption) (*DeleteStudentBankDetailsResponse, error)
	// Bulk operations for stipend processing
	GetStudentsBankDetails(ctx context.Context, in *GetStudentsBankDetailsRequest, opts ...grpc.CallOption) (*GetStudentsBankDetailsResponse, error)
	ValidateBankAccount(ctx context.Context, in *ValidateBankAccountRequest, opts ...grpc.CallOption) (*ValidateBankAccountResponse, error)
}

type bankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankingServiceClient(cc grpc.ClientConnInterface) BankingServiceClient {
	return &bankingServiceClient{cc}
}

func (c *bankingServiceClient) GetBank(ctx context.Context, in *GetBankRequest, opts ...grpc.CallOption) (*GetBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankResponse)
	err := c.cc.Invoke(ctx, BankingService_GetBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) ListBanks(ctx context.Context, in *ListBanksRequest, opts ...grpc.CallOption) (*ListBanksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBanksResponse)
	err := c.cc.Invoke(ctx, BankingService_ListBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) CreateBank(ctx context.Context, in *CreateBankRequest, opts ...grpc.CallOption) (*CreateBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBankResponse)
	err := c.cc.Invoke(ctx, BankingService_CreateBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) UpdateBank(ctx context.Context, in *UpdateBankRequest, opts ...grpc.CallOption) (*UpdateBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBankResponse)
	err := c.cc.Invoke(ctx, BankingService_UpdateBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) DeleteBank(ctx context.Context, in *DeleteBankRequest, opts ...grpc.CallOption) (*DeleteBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBankResponse)
	err := c.cc.Invoke(ctx, BankingService_DeleteBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) GetStudentBankDetails(ctx context.Context, in *GetStudentBankDetailsRequest, opts ...grpc.CallOption) (*GetStudentBankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentBankDetailsResponse)
	err := c.cc.Invoke(ctx, BankingService_GetStudentBankDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) GetStudentBankDetailsByStudentId(ctx context.Context, in *GetStudentBankDetailsByStudentIdRequest, opts ...grpc.CallOption) (*GetStudentBankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentBankDetailsResponse)
	err := c.cc.Invoke(ctx, BankingService_GetStudentBankDetailsByStudentId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) CreateStudentBankDetails(ctx context.Context, in *CreateStudentBankDetailsRequest, opts ...grpc.CallOption) (*CreateStudentBankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStudentBankDetailsResponse)
	err := c.cc.Invoke(ctx, BankingService_CreateStudentBankDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) UpdateStudentBankDetails(ctx context.Context, in *UpdateStudentBankDetailsRequest, opts ...grpc.CallOption) (*UpdateStudentBankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStudentBankDetailsResponse)
	err := c.cc.Invoke(ctx, BankingService_UpdateStudentBankDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) DeleteStudentBankDetails(ctx context.Context, in *DeleteStudentBankDetailsRequest, opts ...grpc.CallOption) (*DeleteStudentBankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStudentBankDetailsResponse)
	err := c.cc.Invoke(ctx, BankingService_DeleteStudentBankDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) GetStudentsBankDetails(ctx context.Context, in *GetStudentsBankDetailsRequest, opts ...grpc.CallOption) (*GetStudentsBankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentsBankDetailsResponse)
	err := c.cc.Invoke(ctx, BankingService_GetStudentsBankDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) ValidateBankAccount(ctx context.Context, in *ValidateBankAccountRequest, opts ...grpc.CallOption) (*ValidateBankAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateBankAccountResponse)
	err := c.cc.Invoke(ctx, BankingService_ValidateBankAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankingServiceServer is the server API for BankingService service.
// All implementations must embed UnimplementedBankingServiceServer
// for forward compatibility.
type BankingServiceServer interface {
	// Bank CRUD operations
	GetBank(context.Context, *GetBankRequest) (*GetBankResponse, error)
	ListBanks(context.Context, *ListBanksRequest) (*ListBanksResponse, error)
	CreateBank(context.Context, *CreateBankRequest) (*CreateBankResponse, error)
	UpdateBank(context.Context, *UpdateBankRequest) (*UpdateBankResponse, error)
	DeleteBank(context.Context, *DeleteBankRequest) (*DeleteBankResponse, error)
	// Student Bank Details operations
	GetStudentBankDetails(context.Context, *GetStudentBankDetailsRequest) (*GetStudentBankDetailsResponse, error)
	GetStudentBankDetailsByStudentId(context.Context, *GetStudentBankDetailsByStudentIdRequest) (*GetStudentBankDetailsResponse, error)
	CreateStudentBankDetails(context.Context, *CreateStudentBankDetailsRequest) (*CreateStudentBankDetailsResponse, error)
	UpdateStudentBankDetails(context.Context, *UpdateStudentBankDetailsRequest) (*UpdateStudentBankDetailsResponse, error)
	DeleteStudentBankDetails(context.Context, *DeleteStudentBankDetailsRequest) (*DeleteStudentBankDetailsResponse, error)
	// Bulk operations for stipend processing
	GetStudentsBankDetails(context.Context, *GetStudentsBankDetailsRequest) (*GetStudentsBankDetailsResponse, error)
	ValidateBankAccount(context.Context, *ValidateBankAccountRequest) (*ValidateBankAccountResponse, error)
	mustEmbedUnimplementedBankingServiceServer()
}

// UnimplementedBankingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankingServiceServer struct{}

func (UnimplementedBankingServiceServer) GetBank(context.Context, *GetBankRequest) (*GetBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBank not implemented")
}
func (UnimplementedBankingServiceServer) ListBanks(context.Context, *ListBanksRequest) (*ListBanksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBanks not implemented")
}
func (UnimplementedBankingServiceServer) CreateBank(context.Context, *CreateBankRequest) (*CreateBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBank not implemented")
}
func (UnimplementedBankingServiceServer) UpdateBank(context.Context, *UpdateBankRequest) (*UpdateBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBank not implemented")
}
func (UnimplementedBankingServiceServer) DeleteBank(context.Context, *DeleteBankRequest) (*DeleteBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBank not implemented")
}
func (UnimplementedBankingServiceServer) GetStudentBankDetails(context.Context, *GetStudentBankDetailsRequest) (*GetStudentBankDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentBankDetails not implemented")
}
func (UnimplementedBankingServiceServer) GetStudentBankDetailsByStudentId(context.Context, *GetStudentBankDetailsByStudentIdRequest) (*GetStudentBankDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentBankDetailsByStudentId not implemented")
}
func (UnimplementedBankingServiceServer) CreateStudentBankDetails(context.Context, *CreateStudentBankDetailsRequest) (*CreateStudentBankDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudentBankDetails not implemented")
}
func (UnimplementedBankingServiceServer) UpdateStudentBankDetails(context.Context, *UpdateStudentBankDetailsRequest) (*UpdateStudentBankDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudentBankDetails not implemented")
}
func (UnimplementedBankingServiceServer) DeleteStudentBankDetails(context.Context, *DeleteStudentBankDetailsRequest) (*DeleteStudentBankDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudentBankDetails not implemented")
}
func (UnimplementedBankingServiceServer) GetStudentsBankDetails(context.Context, *GetStudentsBankDetailsRequest) (*GetStudentsBankDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentsBankDetails not implemented")
}
func (UnimplementedBankingServiceServer) ValidateBankAccount(context.Context, *ValidateBankAccountRequest) (*ValidateBankAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateBankAccount not implemented")
}
func (UnimplementedBankingServiceServer) mustEmbedUnimplementedBankingServiceServer() {}
func (UnimplementedBankingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankingServiceServer will
// result in compilation errors.
type UnsafeBankingServiceServer interface {
	mustEmbedUnimplementedBankingServiceServer()
}

func RegisterBankingServiceServer(s grpc.ServiceRegistrar, srv BankingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBankingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankingService_ServiceDesc, srv)
}

func _BankingService_GetBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).GetBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_GetBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).GetBank(ctx, req.(*GetBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_ListBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBanksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).ListBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_ListBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).ListBanks(ctx, req.(*ListBanksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_CreateBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).CreateBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_CreateBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).CreateBank(ctx, req.(*CreateBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_UpdateBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).UpdateBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_UpdateBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).UpdateBank(ctx, req.(*UpdateBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_DeleteBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).DeleteBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_DeleteBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).DeleteBank(ctx, req.(*DeleteBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_GetStudentBankDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentBankDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).GetStudentBankDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_GetStudentBankDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).GetStudentBankDetails(ctx, req.(*GetStudentBankDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_GetStudentBankDetailsByStudentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentBankDetailsByStudentIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).GetStudentBankDetailsByStudentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_GetStudentBankDetailsByStudentId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).GetStudentBankDetailsByStudentId(ctx, req.(*GetStudentBankDetailsByStudentIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_CreateStudentBankDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentBankDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).CreateStudentBankDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_CreateStudentBankDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).CreateStudentBankDetails(ctx, req.(*CreateStudentBankDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_UpdateStudentBankDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentBankDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).UpdateStudentBankDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_UpdateStudentBankDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).UpdateStudentBankDetails(ctx, req.(*UpdateStudentBankDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_DeleteStudentBankDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentBankDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).DeleteStudentBankDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_DeleteStudentBankDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).DeleteStudentBankDetails(ctx, req.(*DeleteStudentBankDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_GetStudentsBankDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentsBankDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).GetStudentsBankDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_GetStudentsBankDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).GetStudentsBankDetails(ctx, req.(*GetStudentsBankDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_ValidateBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).ValidateBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_ValidateBankAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).ValidateBankAccount(ctx, req.(*ValidateBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankingService_ServiceDesc is the grpc.ServiceDesc for BankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "banking.BankingService",
	HandlerType: (*BankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBank",
			Handler:    _BankingService_GetBank_Handler,
		},
		{
			MethodName: "ListBanks",
			Handler:    _BankingService_ListBanks_Handler,
		},
		{
			MethodName: "CreateBank",
			Handler:    _BankingService_CreateBank_Handler,
		},
		{
			MethodName: "UpdateBank",
			Handler:    _BankingService_UpdateBank_Handler,
		},
		{
			MethodName: "DeleteBank",
			Handler:    _BankingService_DeleteBank_Handler,
		},
		{
			MethodName: "GetStudentBankDetails",
			Handler:    _BankingService_GetStudentBankDetails_Handler,
		},
		{
			MethodName: "GetStudentBankDetailsByStudentId",
			Handler:    _BankingService_GetStudentBankDetailsByStudentId_Handler,
		},
		{
			MethodName: "CreateStudentBankDetails",
			Handler:    _BankingService_CreateStudentBankDetails_Handler,
		},
		{
			MethodName: "UpdateStudentBankDetails",
			Handler:    _BankingService_UpdateStudentBankDetails_Handler,
		},
		{
			MethodName: "DeleteStudentBankDetails",
			Handler:    _BankingService_DeleteStudentBankDetails_Handler,
		},
		{
			MethodName: "GetStudentsBankDetails",
			Handler:    _BankingService_GetStudentsBankDetails_Handler,
		},
		{
			MethodName: "ValidateBankAccount",
			Handler:    _BankingService_ValidateBankAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/banking/banking.proto",
}
