// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/student/student.proto

package student

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request Messages
type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_proto_student_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{0}
}

func (x *GetStudentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStudentByStudentIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentByStudentIdRequest) Reset() {
	*x = GetStudentByStudentIdRequest{}
	mi := &file_proto_student_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentByStudentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentByStudentIdRequest) ProtoMessage() {}

func (x *GetStudentByStudentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentByStudentIdRequest.ProtoReflect.Descriptor instead.
func (*GetStudentByStudentIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{1}
}

func (x *GetStudentByStudentIdRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type CreateStudentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FirstName        string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	StudentId        string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Cid              string                 `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`
	Email            string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth      string                 `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender           string                 `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	ProgramId        uint32                 `protobuf:"varint,9,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	CollegeId        uint32                 `protobuf:"varint,10,opt,name=college_id,json=collegeId,proto3" json:"college_id,omitempty"`
	UserId           uint32                 `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PermanentAddress string                 `protobuf:"bytes,12,opt,name=permanent_address,json=permanentAddress,proto3" json:"permanent_address,omitempty"`
	CurrentAddress   string                 `protobuf:"bytes,13,opt,name=current_address,json=currentAddress,proto3" json:"current_address,omitempty"`
	GuardianName     string                 `protobuf:"bytes,14,opt,name=guardian_name,json=guardianName,proto3" json:"guardian_name,omitempty"`
	GuardianPhone    string                 `protobuf:"bytes,15,opt,name=guardian_phone,json=guardianPhone,proto3" json:"guardian_phone,omitempty"`
	AdmissionDate    string                 `protobuf:"bytes,16,opt,name=admission_date,json=admissionDate,proto3" json:"admission_date,omitempty"`
	EnrollmentStatus string                 `protobuf:"bytes,17,opt,name=enrollment_status,json=enrollmentStatus,proto3" json:"enrollment_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_proto_student_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudentRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateStudentRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateStudentRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *CreateStudentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateStudentRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateStudentRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateStudentRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateStudentRequest) GetProgramId() uint32 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *CreateStudentRequest) GetCollegeId() uint32 {
	if x != nil {
		return x.CollegeId
	}
	return 0
}

func (x *CreateStudentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateStudentRequest) GetPermanentAddress() string {
	if x != nil {
		return x.PermanentAddress
	}
	return ""
}

func (x *CreateStudentRequest) GetCurrentAddress() string {
	if x != nil {
		return x.CurrentAddress
	}
	return ""
}

func (x *CreateStudentRequest) GetGuardianName() string {
	if x != nil {
		return x.GuardianName
	}
	return ""
}

func (x *CreateStudentRequest) GetGuardianPhone() string {
	if x != nil {
		return x.GuardianPhone
	}
	return ""
}

func (x *CreateStudentRequest) GetAdmissionDate() string {
	if x != nil {
		return x.AdmissionDate
	}
	return ""
}

func (x *CreateStudentRequest) GetEnrollmentStatus() string {
	if x != nil {
		return x.EnrollmentStatus
	}
	return ""
}

type UpdateStudentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName        string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email            string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Gender           string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	ProgramId        uint32                 `protobuf:"varint,7,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	CollegeId        uint32                 `protobuf:"varint,8,opt,name=college_id,json=collegeId,proto3" json:"college_id,omitempty"`
	PermanentAddress string                 `protobuf:"bytes,9,opt,name=permanent_address,json=permanentAddress,proto3" json:"permanent_address,omitempty"`
	CurrentAddress   string                 `protobuf:"bytes,10,opt,name=current_address,json=currentAddress,proto3" json:"current_address,omitempty"`
	GuardianName     string                 `protobuf:"bytes,11,opt,name=guardian_name,json=guardianName,proto3" json:"guardian_name,omitempty"`
	GuardianPhone    string                 `protobuf:"bytes,12,opt,name=guardian_phone,json=guardianPhone,proto3" json:"guardian_phone,omitempty"`
	EnrollmentStatus string                 `protobuf:"bytes,13,opt,name=enrollment_status,json=enrollmentStatus,proto3" json:"enrollment_status,omitempty"`
	Gpa              float64                `protobuf:"fixed64,14,opt,name=gpa,proto3" json:"gpa,omitempty"`
	AcademicStanding string                 `protobuf:"bytes,15,opt,name=academic_standing,json=academicStanding,proto3" json:"academic_standing,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateStudentRequest) Reset() {
	*x = UpdateStudentRequest{}
	mi := &file_proto_student_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentRequest) ProtoMessage() {}

func (x *UpdateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStudentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStudentRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateStudentRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateStudentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateStudentRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateStudentRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateStudentRequest) GetProgramId() uint32 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *UpdateStudentRequest) GetCollegeId() uint32 {
	if x != nil {
		return x.CollegeId
	}
	return 0
}

func (x *UpdateStudentRequest) GetPermanentAddress() string {
	if x != nil {
		return x.PermanentAddress
	}
	return ""
}

func (x *UpdateStudentRequest) GetCurrentAddress() string {
	if x != nil {
		return x.CurrentAddress
	}
	return ""
}

func (x *UpdateStudentRequest) GetGuardianName() string {
	if x != nil {
		return x.GuardianName
	}
	return ""
}

func (x *UpdateStudentRequest) GetGuardianPhone() string {
	if x != nil {
		return x.GuardianPhone
	}
	return ""
}

func (x *UpdateStudentRequest) GetEnrollmentStatus() string {
	if x != nil {
		return x.EnrollmentStatus
	}
	return ""
}

func (x *UpdateStudentRequest) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *UpdateStudentRequest) GetAcademicStanding() string {
	if x != nil {
		return x.AcademicStanding
	}
	return ""
}

type DeleteStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentRequest) Reset() {
	*x = DeleteStudentRequest{}
	mi := &file_proto_student_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentRequest) ProtoMessage() {}

func (x *DeleteStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteStudentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsRequest) Reset() {
	*x = ListStudentsRequest{}
	mi := &file_proto_student_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsRequest) ProtoMessage() {}

func (x *ListStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsRequest.ProtoReflect.Descriptor instead.
func (*ListStudentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{5}
}

func (x *ListStudentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SearchStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStudentsRequest) Reset() {
	*x = SearchStudentsRequest{}
	mi := &file_proto_student_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStudentsRequest) ProtoMessage() {}

func (x *SearchStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStudentsRequest.ProtoReflect.Descriptor instead.
func (*SearchStudentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{6}
}

func (x *SearchStudentsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetByProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     uint32                 `protobuf:"varint,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByProgramRequest) Reset() {
	*x = GetByProgramRequest{}
	mi := &file_proto_student_student_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByProgramRequest) ProtoMessage() {}

func (x *GetByProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByProgramRequest.ProtoReflect.Descriptor instead.
func (*GetByProgramRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{7}
}

func (x *GetByProgramRequest) GetProgramId() uint32 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

type GetByCollegeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollegeId     uint32                 `protobuf:"varint,1,opt,name=college_id,json=collegeId,proto3" json:"college_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByCollegeRequest) Reset() {
	*x = GetByCollegeRequest{}
	mi := &file_proto_student_student_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByCollegeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByCollegeRequest) ProtoMessage() {}

func (x *GetByCollegeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByCollegeRequest.ProtoReflect.Descriptor instead.
func (*GetByCollegeRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{8}
}

func (x *GetByCollegeRequest) GetCollegeId() uint32 {
	if x != nil {
		return x.CollegeId
	}
	return 0
}

type StipendEligibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     uint32                 `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StipendEligibilityRequest) Reset() {
	*x = StipendEligibilityRequest{}
	mi := &file_proto_student_student_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StipendEligibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StipendEligibilityRequest) ProtoMessage() {}

func (x *StipendEligibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StipendEligibilityRequest.ProtoReflect.Descriptor instead.
func (*StipendEligibilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{9}
}

func (x *StipendEligibilityRequest) GetStudentId() uint32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

// Response Messages
type StudentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName        string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	StudentId        string                 `protobuf:"bytes,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Cid              string                 `protobuf:"bytes,5,opt,name=cid,proto3" json:"cid,omitempty"`
	Email            string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth      string                 `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender           string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	ProgramId        uint32                 `protobuf:"varint,10,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	CollegeId        uint32                 `protobuf:"varint,11,opt,name=college_id,json=collegeId,proto3" json:"college_id,omitempty"`
	UserId           uint32                 `protobuf:"varint,12,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PermanentAddress string                 `protobuf:"bytes,13,opt,name=permanent_address,json=permanentAddress,proto3" json:"permanent_address,omitempty"`
	CurrentAddress   string                 `protobuf:"bytes,14,opt,name=current_address,json=currentAddress,proto3" json:"current_address,omitempty"`
	GuardianName     string                 `protobuf:"bytes,15,opt,name=guardian_name,json=guardianName,proto3" json:"guardian_name,omitempty"`
	GuardianPhone    string                 `protobuf:"bytes,16,opt,name=guardian_phone,json=guardianPhone,proto3" json:"guardian_phone,omitempty"`
	AdmissionDate    string                 `protobuf:"bytes,17,opt,name=admission_date,json=admissionDate,proto3" json:"admission_date,omitempty"`
	EnrollmentStatus string                 `protobuf:"bytes,18,opt,name=enrollment_status,json=enrollmentStatus,proto3" json:"enrollment_status,omitempty"`
	Gpa              float64                `protobuf:"fixed64,19,opt,name=gpa,proto3" json:"gpa,omitempty"`
	AcademicStanding string                 `protobuf:"bytes,20,opt,name=academic_standing,json=academicStanding,proto3" json:"academic_standing,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StudentResponse) Reset() {
	*x = StudentResponse{}
	mi := &file_proto_student_student_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentResponse) ProtoMessage() {}

func (x *StudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentResponse.ProtoReflect.Descriptor instead.
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{10}
}

func (x *StudentResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *StudentResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *StudentResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentResponse) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *StudentResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StudentResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *StudentResponse) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *StudentResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *StudentResponse) GetProgramId() uint32 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *StudentResponse) GetCollegeId() uint32 {
	if x != nil {
		return x.CollegeId
	}
	return 0
}

func (x *StudentResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StudentResponse) GetPermanentAddress() string {
	if x != nil {
		return x.PermanentAddress
	}
	return ""
}

func (x *StudentResponse) GetCurrentAddress() string {
	if x != nil {
		return x.CurrentAddress
	}
	return ""
}

func (x *StudentResponse) GetGuardianName() string {
	if x != nil {
		return x.GuardianName
	}
	return ""
}

func (x *StudentResponse) GetGuardianPhone() string {
	if x != nil {
		return x.GuardianPhone
	}
	return ""
}

func (x *StudentResponse) GetAdmissionDate() string {
	if x != nil {
		return x.AdmissionDate
	}
	return ""
}

func (x *StudentResponse) GetEnrollmentStatus() string {
	if x != nil {
		return x.EnrollmentStatus
	}
	return ""
}

func (x *StudentResponse) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *StudentResponse) GetAcademicStanding() string {
	if x != nil {
		return x.AcademicStanding
	}
	return ""
}

func (x *StudentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StudentResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListStudentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*StudentResponse     `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsResponse) Reset() {
	*x = ListStudentsResponse{}
	mi := &file_proto_student_student_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsResponse) ProtoMessage() {}

func (x *ListStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsResponse.ProtoReflect.Descriptor instead.
func (*ListStudentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{11}
}

func (x *ListStudentsResponse) GetStudents() []*StudentResponse {
	if x != nil {
		return x.Students
	}
	return nil
}

func (x *ListStudentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_student_student_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StipendEligibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eligible      bool                   `protobuf:"varint,1,opt,name=eligible,proto3" json:"eligible,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	StipendType   string                 `protobuf:"bytes,4,opt,name=stipend_type,json=stipendType,proto3" json:"stipend_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StipendEligibilityResponse) Reset() {
	*x = StipendEligibilityResponse{}
	mi := &file_proto_student_student_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StipendEligibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StipendEligibilityResponse) ProtoMessage() {}

func (x *StipendEligibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_student_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StipendEligibilityResponse.ProtoReflect.Descriptor instead.
func (*StipendEligibilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_student_student_proto_rawDescGZIP(), []int{13}
}

func (x *StipendEligibilityResponse) GetEligible() bool {
	if x != nil {
		return x.Eligible
	}
	return false
}

func (x *StipendEligibilityResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StipendEligibilityResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StipendEligibilityResponse) GetStipendType() string {
	if x != nil {
		return x.StipendType
	}
	return ""
}

var File_proto_student_student_proto protoreflect.FileDescriptor

const file_proto_student_student_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/student/student.proto\x12\astudent\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\x11GetStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"=\n" +
	"\x1cGetStudentByStudentIdRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"\xc5\x04\n" +
	"\x14CreateStudentRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x10\n" +
	"\x03cid\x18\x04 \x01(\tR\x03cid\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\"\n" +
	"\rdate_of_birth\x18\a \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\b \x01(\tR\x06gender\x12\x1d\n" +
	"\n" +
	"program_id\x18\t \x01(\rR\tprogramId\x12\x1d\n" +
	"\n" +
	"college_id\x18\n" +
	" \x01(\rR\tcollegeId\x12\x17\n" +
	"\auser_id\x18\v \x01(\rR\x06userId\x12+\n" +
	"\x11permanent_address\x18\f \x01(\tR\x10permanentAddress\x12'\n" +
	"\x0fcurrent_address\x18\r \x01(\tR\x0ecurrentAddress\x12#\n" +
	"\rguardian_name\x18\x0e \x01(\tR\fguardianName\x12%\n" +
	"\x0eguardian_phone\x18\x0f \x01(\tR\rguardianPhone\x12%\n" +
	"\x0eadmission_date\x18\x10 \x01(\tR\radmissionDate\x12+\n" +
	"\x11enrollment_status\x18\x11 \x01(\tR\x10enrollmentStatus\"\xff\x03\n" +
	"\x14UpdateStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x1d\n" +
	"\n" +
	"program_id\x18\a \x01(\rR\tprogramId\x12\x1d\n" +
	"\n" +
	"college_id\x18\b \x01(\rR\tcollegeId\x12+\n" +
	"\x11permanent_address\x18\t \x01(\tR\x10permanentAddress\x12'\n" +
	"\x0fcurrent_address\x18\n" +
	" \x01(\tR\x0ecurrentAddress\x12#\n" +
	"\rguardian_name\x18\v \x01(\tR\fguardianName\x12%\n" +
	"\x0eguardian_phone\x18\f \x01(\tR\rguardianPhone\x12+\n" +
	"\x11enrollment_status\x18\r \x01(\tR\x10enrollmentStatus\x12\x10\n" +
	"\x03gpa\x18\x0e \x01(\x01R\x03gpa\x12+\n" +
	"\x11academic_standing\x18\x0f \x01(\tR\x10academicStanding\"&\n" +
	"\x14DeleteStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"-\n" +
	"\x13ListStudentsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"-\n" +
	"\x15SearchStudentsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"4\n" +
	"\x13GetByProgramRequest\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\rR\tprogramId\"4\n" +
	"\x13GetByCollegeRequest\x12\x1d\n" +
	"\n" +
	"college_id\x18\x01 \x01(\rR\tcollegeId\":\n" +
	"\x19StipendEligibilityRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\rR\tstudentId\"\x85\x06\n" +
	"\x0fStudentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"student_id\x18\x04 \x01(\tR\tstudentId\x12\x10\n" +
	"\x03cid\x18\x05 \x01(\tR\x03cid\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\"\n" +
	"\rdate_of_birth\x18\b \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x1d\n" +
	"\n" +
	"program_id\x18\n" +
	" \x01(\rR\tprogramId\x12\x1d\n" +
	"\n" +
	"college_id\x18\v \x01(\rR\tcollegeId\x12\x17\n" +
	"\auser_id\x18\f \x01(\rR\x06userId\x12+\n" +
	"\x11permanent_address\x18\r \x01(\tR\x10permanentAddress\x12'\n" +
	"\x0fcurrent_address\x18\x0e \x01(\tR\x0ecurrentAddress\x12#\n" +
	"\rguardian_name\x18\x0f \x01(\tR\fguardianName\x12%\n" +
	"\x0eguardian_phone\x18\x10 \x01(\tR\rguardianPhone\x12%\n" +
	"\x0eadmission_date\x18\x11 \x01(\tR\radmissionDate\x12+\n" +
	"\x11enrollment_status\x18\x12 \x01(\tR\x10enrollmentStatus\x12\x10\n" +
	"\x03gpa\x18\x13 \x01(\x01R\x03gpa\x12+\n" +
	"\x11academic_standing\x18\x14 \x01(\tR\x10academicStanding\x129\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"b\n" +
	"\x14ListStudentsResponse\x124\n" +
	"\bstudents\x18\x01 \x03(\v2\x18.student.StudentResponseR\bstudents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x1aStipendEligibilityResponse\x12\x1a\n" +
	"\beligible\x18\x01 \x01(\bR\beligible\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12!\n" +
	"\fstipend_type\x18\x04 \x01(\tR\vstipendType2\xb7\x06\n" +
	"\x0eStudentService\x12B\n" +
	"\n" +
	"GetStudent\x12\x1a.student.GetStudentRequest\x1a\x18.student.StudentResponse\x12X\n" +
	"\x15GetStudentByStudentId\x12%.student.GetStudentByStudentIdRequest\x1a\x18.student.StudentResponse\x12H\n" +
	"\rCreateStudent\x12\x1d.student.CreateStudentRequest\x1a\x18.student.StudentResponse\x12H\n" +
	"\rUpdateStudent\x12\x1d.student.UpdateStudentRequest\x1a\x18.student.StudentResponse\x12G\n" +
	"\rDeleteStudent\x12\x1d.student.DeleteStudentRequest\x1a\x17.student.DeleteResponse\x12K\n" +
	"\fListStudents\x12\x1c.student.ListStudentsRequest\x1a\x1d.student.ListStudentsResponse\x12O\n" +
	"\x0eSearchStudents\x12\x1e.student.SearchStudentsRequest\x1a\x1d.student.ListStudentsResponse\x12S\n" +
	"\x14GetStudentsByProgram\x12\x1c.student.GetByProgramRequest\x1a\x1d.student.ListStudentsResponse\x12S\n" +
	"\x14GetStudentsByCollege\x12\x1c.student.GetByCollegeRequest\x1a\x1d.student.ListStudentsResponse\x12b\n" +
	"\x17CheckStipendEligibility\x12\".student.StipendEligibilityRequest\x1a#.student.StipendEligibilityResponseB'Z%student_management_service/pb/studentb\x06proto3"

var (
	file_proto_student_student_proto_rawDescOnce sync.Once
	file_proto_student_student_proto_rawDescData []byte
)

func file_proto_student_student_proto_rawDescGZIP() []byte {
	file_proto_student_student_proto_rawDescOnce.Do(func() {
		file_proto_student_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_student_student_proto_rawDesc), len(file_proto_student_student_proto_rawDesc)))
	})
	return file_proto_student_student_proto_rawDescData
}

var file_proto_student_student_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_student_student_proto_goTypes = []any{
	(*GetStudentRequest)(nil),            // 0: student.GetStudentRequest
	(*GetStudentByStudentIdRequest)(nil), // 1: student.GetStudentByStudentIdRequest
	(*CreateStudentRequest)(nil),         // 2: student.CreateStudentRequest
	(*UpdateStudentRequest)(nil),         // 3: student.UpdateStudentRequest
	(*DeleteStudentRequest)(nil),         // 4: student.DeleteStudentRequest
	(*ListStudentsRequest)(nil),          // 5: student.ListStudentsRequest
	(*SearchStudentsRequest)(nil),        // 6: student.SearchStudentsRequest
	(*GetByProgramRequest)(nil),          // 7: student.GetByProgramRequest
	(*GetByCollegeRequest)(nil),          // 8: student.GetByCollegeRequest
	(*StipendEligibilityRequest)(nil),    // 9: student.StipendEligibilityRequest
	(*StudentResponse)(nil),              // 10: student.StudentResponse
	(*ListStudentsResponse)(nil),         // 11: student.ListStudentsResponse
	(*DeleteResponse)(nil),               // 12: student.DeleteResponse
	(*StipendEligibilityResponse)(nil),   // 13: student.StipendEligibilityResponse
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
}
var file_proto_student_student_proto_depIdxs = []int32{
	14, // 0: student.StudentResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: student.StudentResponse.updated_at:type_name -> google.protobuf.Timestamp
	10, // 2: student.ListStudentsResponse.students:type_name -> student.StudentResponse
	0,  // 3: student.StudentService.GetStudent:input_type -> student.GetStudentRequest
	1,  // 4: student.StudentService.GetStudentByStudentId:input_type -> student.GetStudentByStudentIdRequest
	2,  // 5: student.StudentService.CreateStudent:input_type -> student.CreateStudentRequest
	3,  // 6: student.StudentService.UpdateStudent:input_type -> student.UpdateStudentRequest
	4,  // 7: student.StudentService.DeleteStudent:input_type -> student.DeleteStudentRequest
	5,  // 8: student.StudentService.ListStudents:input_type -> student.ListStudentsRequest
	6,  // 9: student.StudentService.SearchStudents:input_type -> student.SearchStudentsRequest
	7,  // 10: student.StudentService.GetStudentsByProgram:input_type -> student.GetByProgramRequest
	8,  // 11: student.StudentService.GetStudentsByCollege:input_type -> student.GetByCollegeRequest
	9,  // 12: student.StudentService.CheckStipendEligibility:input_type -> student.StipendEligibilityRequest
	10, // 13: student.StudentService.GetStudent:output_type -> student.StudentResponse
	10, // 14: student.StudentService.GetStudentByStudentId:output_type -> student.StudentResponse
	10, // 15: student.StudentService.CreateStudent:output_type -> student.StudentResponse
	10, // 16: student.StudentService.UpdateStudent:output_type -> student.StudentResponse
	12, // 17: student.StudentService.DeleteStudent:output_type -> student.DeleteResponse
	11, // 18: student.StudentService.ListStudents:output_type -> student.ListStudentsResponse
	11, // 19: student.StudentService.SearchStudents:output_type -> student.ListStudentsResponse
	11, // 20: student.StudentService.GetStudentsByProgram:output_type -> student.ListStudentsResponse
	11, // 21: student.StudentService.GetStudentsByCollege:output_type -> student.ListStudentsResponse
	13, // 22: student.StudentService.CheckStipendEligibility:output_type -> student.StipendEligibilityResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_student_student_proto_init() }
func file_proto_student_student_proto_init() {
	if File_proto_student_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_student_student_proto_rawDesc), len(file_proto_student_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_student_student_proto_goTypes,
		DependencyIndexes: file_proto_student_student_proto_depIdxs,
		MessageInfos:      file_proto_student_student_proto_msgTypes,
	}.Build()
	File_proto_student_student_proto = out.File
	file_proto_student_student_proto_goTypes = nil
	file_proto_student_student_proto_depIdxs = nil
}
