// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/banking/banking.proto

package banking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBankDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     uint32                 `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankDetailsRequest) Reset() {
	*x = GetBankDetailsRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankDetailsRequest) ProtoMessage() {}

func (x *GetBankDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetBankDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{0}
}

func (x *GetBankDetailsRequest) GetStudentId() uint32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type UpsertBankDetailsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StudentId         uint32                 `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	BankId            uint32                 `protobuf:"varint,2,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolderName string                 `protobuf:"bytes,4,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertBankDetailsRequest) Reset() {
	*x = UpsertBankDetailsRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertBankDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBankDetailsRequest) ProtoMessage() {}

func (x *UpsertBankDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBankDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpsertBankDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertBankDetailsRequest) GetStudentId() uint32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *UpsertBankDetailsRequest) GetBankId() uint32 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *UpsertBankDetailsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UpsertBankDetailsRequest) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

type VerifyBankAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	BankId        uint32                 `protobuf:"varint,2,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBankAccountRequest) Reset() {
	*x = VerifyBankAccountRequest{}
	mi := &file_proto_banking_banking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBankAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBankAccountRequest) ProtoMessage() {}

func (x *VerifyBankAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBankAccountRequest.ProtoReflect.Descriptor instead.
func (*VerifyBankAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyBankAccountRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *VerifyBankAccountRequest) GetBankId() uint32 {
	if x != nil {
		return x.BankId
	}
	return 0
}

type BankDetailsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId         uint32                 `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	BankId            uint32                 `protobuf:"varint,3,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	BankName          string                 `protobuf:"bytes,4,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,5,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolderName string                 `protobuf:"bytes,6,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	Verified          bool                   `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BankDetailsResponse) Reset() {
	*x = BankDetailsResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankDetailsResponse) ProtoMessage() {}

func (x *BankDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankDetailsResponse.ProtoReflect.Descriptor instead.
func (*BankDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{3}
}

func (x *BankDetailsResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BankDetailsResponse) GetStudentId() uint32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *BankDetailsResponse) GetBankId() uint32 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *BankDetailsResponse) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *BankDetailsResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BankDetailsResponse) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

func (x *BankDetailsResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type VerifyBankAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBankAccountResponse) Reset() {
	*x = VerifyBankAccountResponse{}
	mi := &file_proto_banking_banking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBankAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBankAccountResponse) ProtoMessage() {}

func (x *VerifyBankAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banking_banking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBankAccountResponse.ProtoReflect.Descriptor instead.
func (*VerifyBankAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_banking_banking_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyBankAccountResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyBankAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_banking_banking_proto protoreflect.FileDescriptor

const file_proto_banking_banking_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/banking/banking.proto\x12\abanking\"6\n" +
	"\x15GetBankDetailsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\rR\tstudentId\"\xa9\x01\n" +
	"\x18UpsertBankDetailsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\rR\tstudentId\x12\x17\n" +
	"\abank_id\x18\x02 \x01(\rR\x06bankId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12.\n" +
	"\x13account_holder_name\x18\x04 \x01(\tR\x11accountHolderName\"Z\n" +
	"\x18VerifyBankAccountRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x17\n" +
	"\abank_id\x18\x02 \x01(\rR\x06bankId\"\xed\x01\n" +
	"\x13BankDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\rR\tstudentId\x12\x17\n" +
	"\abank_id\x18\x03 \x01(\rR\x06bankId\x12\x1b\n" +
	"\tbank_name\x18\x04 \x01(\tR\bbankName\x12%\n" +
	"\x0eaccount_number\x18\x05 \x01(\tR\raccountNumber\x12.\n" +
	"\x13account_holder_name\x18\x06 \x01(\tR\x11accountHolderName\x12\x1a\n" +
	"\bverified\x18\a \x01(\bR\bverified\"K\n" +
	"\x19VerifyBankAccountResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x99\x02\n" +
	"\x0eBankingService\x12U\n" +
	"\x15GetStudentBankDetails\x12\x1e.banking.GetBankDetailsRequest\x1a\x1c.banking.BankDetailsResponse\x12T\n" +
	"\x11UpsertBankDetails\x12!.banking.UpsertBankDetailsRequest\x1a\x1c.banking.BankDetailsResponse\x12Z\n" +
	"\x11VerifyBankAccount\x12!.banking.VerifyBankAccountRequest\x1a\".banking.VerifyBankAccountResponseB\x1dZ\x1bbanking_services/pb/bankingb\x06proto3"

var (
	file_proto_banking_banking_proto_rawDescOnce sync.Once
	file_proto_banking_banking_proto_rawDescData []byte
)

func file_proto_banking_banking_proto_rawDescGZIP() []byte {
	file_proto_banking_banking_proto_rawDescOnce.Do(func() {
		file_proto_banking_banking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_banking_banking_proto_rawDesc), len(file_proto_banking_banking_proto_rawDesc)))
	})
	return file_proto_banking_banking_proto_rawDescData
}

var file_proto_banking_banking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_banking_banking_proto_goTypes = []any{
	(*GetBankDetailsRequest)(nil),     // 0: banking.GetBankDetailsRequest
	(*UpsertBankDetailsRequest)(nil),  // 1: banking.UpsertBankDetailsRequest
	(*VerifyBankAccountRequest)(nil),  // 2: banking.VerifyBankAccountRequest
	(*BankDetailsResponse)(nil),       // 3: banking.BankDetailsResponse
	(*VerifyBankAccountResponse)(nil), // 4: banking.VerifyBankAccountResponse
}
var file_proto_banking_banking_proto_depIdxs = []int32{
	0, // 0: banking.BankingService.GetStudentBankDetails:input_type -> banking.GetBankDetailsRequest
	1, // 1: banking.BankingService.UpsertBankDetails:input_type -> banking.UpsertBankDetailsRequest
	2, // 2: banking.BankingService.VerifyBankAccount:input_type -> banking.VerifyBankAccountRequest
	3, // 3: banking.BankingService.GetStudentBankDetails:output_type -> banking.BankDetailsResponse
	3, // 4: banking.BankingService.UpsertBankDetails:output_type -> banking.BankDetailsResponse
	4, // 5: banking.BankingService.VerifyBankAccount:output_type -> banking.VerifyBankAccountResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_banking_banking_proto_init() }
func file_proto_banking_banking_proto_init() {
	if File_proto_banking_banking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_banking_banking_proto_rawDesc), len(file_proto_banking_banking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_banking_banking_proto_goTypes,
		DependencyIndexes: file_proto_banking_banking_proto_depIdxs,
		MessageInfos:      file_proto_banking_banking_proto_msgTypes,
	}.Build()
	File_proto_banking_banking_proto = out.File
	file_proto_banking_banking_proto_goTypes = nil
	file_proto_banking_banking_proto_depIdxs = nil
}
