// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/banking/banking.proto

package banking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankingService_GetStudentBankDetails_FullMethodName = "/banking.BankingService/GetStudentBankDetails"
	BankingService_UpsertBankDetails_FullMethodName     = "/banking.BankingService/UpsertBankDetails"
	BankingService_VerifyBankAccount_FullMethodName     = "/banking.BankingService/VerifyBankAccount"
)

// BankingServiceClient is the client API for BankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Banking Service - Manages bank accounts and student bank details
type BankingServiceClient interface {
	// Get bank details for a student
	GetStudentBankDetails(ctx context.Context, in *GetBankDetailsRequest, opts ...grpc.CallOption) (*BankDetailsResponse, error)
	// Create or update bank details
	UpsertBankDetails(ctx context.Context, in *UpsertBankDetailsRequest, opts ...grpc.CallOption) (*BankDetailsResponse, error)
	// Verify bank account exists
	VerifyBankAccount(ctx context.Context, in *VerifyBankAccountRequest, opts ...grpc.CallOption) (*VerifyBankAccountResponse, error)
}

type bankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankingServiceClient(cc grpc.ClientConnInterface) BankingServiceClient {
	return &bankingServiceClient{cc}
}

func (c *bankingServiceClient) GetStudentBankDetails(ctx context.Context, in *GetBankDetailsRequest, opts ...grpc.CallOption) (*BankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankDetailsResponse)
	err := c.cc.Invoke(ctx, BankingService_GetStudentBankDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) UpsertBankDetails(ctx context.Context, in *UpsertBankDetailsRequest, opts ...grpc.CallOption) (*BankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankDetailsResponse)
	err := c.cc.Invoke(ctx, BankingService_UpsertBankDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingServiceClient) VerifyBankAccount(ctx context.Context, in *VerifyBankAccountRequest, opts ...grpc.CallOption) (*VerifyBankAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyBankAccountResponse)
	err := c.cc.Invoke(ctx, BankingService_VerifyBankAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankingServiceServer is the server API for BankingService service.
// All implementations must embed UnimplementedBankingServiceServer
// for forward compatibility.
//
// Banking Service - Manages bank accounts and student bank details
type BankingServiceServer interface {
	// Get bank details for a student
	GetStudentBankDetails(context.Context, *GetBankDetailsRequest) (*BankDetailsResponse, error)
	// Create or update bank details
	UpsertBankDetails(context.Context, *UpsertBankDetailsRequest) (*BankDetailsResponse, error)
	// Verify bank account exists
	VerifyBankAccount(context.Context, *VerifyBankAccountRequest) (*VerifyBankAccountResponse, error)
	mustEmbedUnimplementedBankingServiceServer()
}

// UnimplementedBankingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankingServiceServer struct{}

func (UnimplementedBankingServiceServer) GetStudentBankDetails(context.Context, *GetBankDetailsRequest) (*BankDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentBankDetails not implemented")
}
func (UnimplementedBankingServiceServer) UpsertBankDetails(context.Context, *UpsertBankDetailsRequest) (*BankDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertBankDetails not implemented")
}
func (UnimplementedBankingServiceServer) VerifyBankAccount(context.Context, *VerifyBankAccountRequest) (*VerifyBankAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBankAccount not implemented")
}
func (UnimplementedBankingServiceServer) mustEmbedUnimplementedBankingServiceServer() {}
func (UnimplementedBankingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankingServiceServer will
// result in compilation errors.
type UnsafeBankingServiceServer interface {
	mustEmbedUnimplementedBankingServiceServer()
}

func RegisterBankingServiceServer(s grpc.ServiceRegistrar, srv BankingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBankingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankingService_ServiceDesc, srv)
}

func _BankingService_GetStudentBankDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).GetStudentBankDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_GetStudentBankDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).GetStudentBankDetails(ctx, req.(*GetBankDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_UpsertBankDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertBankDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).UpsertBankDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_UpsertBankDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).UpsertBankDetails(ctx, req.(*UpsertBankDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankingService_VerifyBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServiceServer).VerifyBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankingService_VerifyBankAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServiceServer).VerifyBankAccount(ctx, req.(*VerifyBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankingService_ServiceDesc is the grpc.ServiceDesc for BankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "banking.BankingService",
	HandlerType: (*BankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentBankDetails",
			Handler:    _BankingService_GetStudentBankDetails_Handler,
		},
		{
			MethodName: "UpsertBankDetails",
			Handler:    _BankingService_UpsertBankDetails_Handler,
		},
		{
			MethodName: "VerifyBankAccount",
			Handler:    _BankingService_VerifyBankAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/banking/banking.proto",
}
