// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//  protoc-gen-go v1.28.1
//  protoc        v3.12.0
// source: student.proto

package student

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - iota)
	_ = protoimpl.EnforceVersion(iota)
)

type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32
	StudentId string
	FirstName string
	LastName  string
	Email     string
}

func (x *Student) Reset() {
	*x = Student{}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageState(x)
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var file_student_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_student_proto_goTypes = []interface{}{
	(*Student)(nil),
}
var file_student_proto_depIdxs = []int32{
	0,
}

var (
	file_student_proto_rawDesc = []byte{
		0x0a, 0x0d, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	}
)

var (
	file_student_proto_once sync.Once
	file_student_proto_mutex = &sync.Mutex{}
)

func file_student_proto_init() {
	if file_student_proto_rawDesc != nil {
		return
	}
}

type GetStudentRequest struct {
	StudentId string
}

type GetStudentResponse struct {
	Student *Student
}
