// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: deduction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeductionRuleType defines applicable deduction rule types
type DeductionRuleType int32

const (
	DeductionRuleType_DEDUCTION_RULE_TYPE_UNSPECIFIED DeductionRuleType = 0
	DeductionRuleType_HOSTEL                          DeductionRuleType = 1
	DeductionRuleType_ELECTRICITY                     DeductionRuleType = 2
	DeductionRuleType_MESS_FEES                       DeductionRuleType = 3
	DeductionRuleType_WATER                           DeductionRuleType = 4
	DeductionRuleType_MAINTENANCE                     DeductionRuleType = 5
	DeductionRuleType_OTHER                           DeductionRuleType = 6
)

// Enum value maps for DeductionRuleType.
var (
	DeductionRuleType_name = map[int32]string{
		0: "DEDUCTION_RULE_TYPE_UNSPECIFIED",
		1: "HOSTEL",
		2: "ELECTRICITY",
		3: "MESS_FEES",
		4: "WATER",
		5: "MAINTENANCE",
		6: "OTHER",
	}
	DeductionRuleType_value = map[string]int32{
		"DEDUCTION_RULE_TYPE_UNSPECIFIED": 0,
		"HOSTEL":                          1,
		"ELECTRICITY":                     2,
		"MESS_FEES":                       3,
		"WATER":                           4,
		"MAINTENANCE":                     5,
		"OTHER":                           6,
	}
)

func (x DeductionRuleType) Enum() *DeductionRuleType {
	p := new(DeductionRuleType)
	*p = x
	return p
}

func (x DeductionRuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeductionRuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_deduction_proto_enumTypes[0].Descriptor()
}

func (DeductionRuleType) Type() protoreflect.EnumType {
	return &file_deduction_proto_enumTypes[0]
}

func (x DeductionRuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeductionRuleType.Descriptor instead.
func (DeductionRuleType) EnumDescriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{0}
}

// ApplicableStudentType defines which student types a rule applies to
type ApplicableStudentType int32

const (
	ApplicableStudentType_APPLICABLE_STUDENT_TYPE_UNSPECIFIED ApplicableStudentType = 0
	ApplicableStudentType_ALL                                 ApplicableStudentType = 1
	ApplicableStudentType_FULL_SCHOLARSHIP                    ApplicableStudentType = 2
	ApplicableStudentType_SELF_FUNDED                         ApplicableStudentType = 3
)

// Enum value maps for ApplicableStudentType.
var (
	ApplicableStudentType_name = map[int32]string{
		0: "APPLICABLE_STUDENT_TYPE_UNSPECIFIED",
		1: "ALL",
		2: "FULL_SCHOLARSHIP",
		3: "SELF_FUNDED",
	}
	ApplicableStudentType_value = map[string]int32{
		"APPLICABLE_STUDENT_TYPE_UNSPECIFIED": 0,
		"ALL":                                 1,
		"FULL_SCHOLARSHIP":                    2,
		"SELF_FUNDED":                         3,
	}
)

func (x ApplicableStudentType) Enum() *ApplicableStudentType {
	p := new(ApplicableStudentType)
	*p = x
	return p
}

func (x ApplicableStudentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicableStudentType) Descriptor() protoreflect.EnumDescriptor {
	return file_deduction_proto_enumTypes[1].Descriptor()
}

func (ApplicableStudentType) Type() protoreflect.EnumType {
	return &file_deduction_proto_enumTypes[1]
}

func (x ApplicableStudentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicableStudentType.Descriptor instead.
func (ApplicableStudentType) EnumDescriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{1}
}

// CreateDeductionRuleRequest represents a request to create a deduction rule
type CreateDeductionRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleName      string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	DeductionType string                 `protobuf:"bytes,2,opt,name=deduction_type,json=deductionType,proto3" json:"deduction_type,omitempty"`
	DefaultAmount float64                `protobuf:"fixed64,3,opt,name=default_amount,json=defaultAmount,proto3" json:"default_amount,omitempty"`
	MinAmount     float64                `protobuf:"fixed64,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     float64                `protobuf:"fixed64,5,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	Frequency     string                 `protobuf:"bytes,6,opt,name=frequency,proto3" json:"frequency,omitempty"` // "Monthly", "Annual", "OneTime"
	IsMandatory   bool                   `protobuf:"varint,7,opt,name=is_mandatory,json=isMandatory,proto3" json:"is_mandatory,omitempty"`
	ApplicableTo  string                 `protobuf:"bytes,8,opt,name=applicable_to,json=applicableTo,proto3" json:"applicable_to,omitempty"` // "All", "FullScholarship", "SelfFunded"
	Priority      int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeductionRuleRequest) Reset() {
	*x = CreateDeductionRuleRequest{}
	mi := &file_deduction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeductionRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeductionRuleRequest) ProtoMessage() {}

func (x *CreateDeductionRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeductionRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateDeductionRuleRequest) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDeductionRuleRequest) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *CreateDeductionRuleRequest) GetDeductionType() string {
	if x != nil {
		return x.DeductionType
	}
	return ""
}

func (x *CreateDeductionRuleRequest) GetDefaultAmount() float64 {
	if x != nil {
		return x.DefaultAmount
	}
	return 0
}

func (x *CreateDeductionRuleRequest) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CreateDeductionRuleRequest) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *CreateDeductionRuleRequest) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *CreateDeductionRuleRequest) GetIsMandatory() bool {
	if x != nil {
		return x.IsMandatory
	}
	return false
}

func (x *CreateDeductionRuleRequest) GetApplicableTo() string {
	if x != nil {
		return x.ApplicableTo
	}
	return ""
}

func (x *CreateDeductionRuleRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateDeductionRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// DeductionRuleResponse represents a deduction rule
type DeductionRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	DeductionType string                 `protobuf:"bytes,3,opt,name=deduction_type,json=deductionType,proto3" json:"deduction_type,omitempty"`
	DefaultAmount float64                `protobuf:"fixed64,4,opt,name=default_amount,json=defaultAmount,proto3" json:"default_amount,omitempty"`
	MinAmount     float64                `protobuf:"fixed64,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     float64                `protobuf:"fixed64,6,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	Frequency     string                 `protobuf:"bytes,7,opt,name=frequency,proto3" json:"frequency,omitempty"`
	IsMandatory   bool                   `protobuf:"varint,8,opt,name=is_mandatory,json=isMandatory,proto3" json:"is_mandatory,omitempty"`
	ApplicableTo  string                 `protobuf:"bytes,9,opt,name=applicable_to,json=applicableTo,proto3" json:"applicable_to,omitempty"`
	Priority      int32                  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	Description   string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // Unix timestamp
	ModifiedAt    int64                  `protobuf:"varint,14,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductionRuleResponse) Reset() {
	*x = DeductionRuleResponse{}
	mi := &file_deduction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductionRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductionRuleResponse) ProtoMessage() {}

func (x *DeductionRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductionRuleResponse.ProtoReflect.Descriptor instead.
func (*DeductionRuleResponse) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{1}
}

func (x *DeductionRuleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeductionRuleResponse) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *DeductionRuleResponse) GetDeductionType() string {
	if x != nil {
		return x.DeductionType
	}
	return ""
}

func (x *DeductionRuleResponse) GetDefaultAmount() float64 {
	if x != nil {
		return x.DefaultAmount
	}
	return 0
}

func (x *DeductionRuleResponse) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *DeductionRuleResponse) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *DeductionRuleResponse) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *DeductionRuleResponse) GetIsMandatory() bool {
	if x != nil {
		return x.IsMandatory
	}
	return false
}

func (x *DeductionRuleResponse) GetApplicableTo() string {
	if x != nil {
		return x.ApplicableTo
	}
	return ""
}

func (x *DeductionRuleResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DeductionRuleResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeductionRuleResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *DeductionRuleResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DeductionRuleResponse) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

// GetDeductionRuleRequest represents a request to get a deduction rule
type GetDeductionRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeductionRuleRequest) Reset() {
	*x = GetDeductionRuleRequest{}
	mi := &file_deduction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeductionRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeductionRuleRequest) ProtoMessage() {}

func (x *GetDeductionRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeductionRuleRequest.ProtoReflect.Descriptor instead.
func (*GetDeductionRuleRequest) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeductionRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

// ListDeductionRulesRequest represents a request to list deduction rules
type ListDeductionRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicableTo  string                 `protobuf:"bytes,1,opt,name=applicable_to,json=applicableTo,proto3" json:"applicable_to,omitempty"` // Optional filter
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeductionRulesRequest) Reset() {
	*x = ListDeductionRulesRequest{}
	mi := &file_deduction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeductionRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeductionRulesRequest) ProtoMessage() {}

func (x *ListDeductionRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeductionRulesRequest.ProtoReflect.Descriptor instead.
func (*ListDeductionRulesRequest) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{3}
}

func (x *ListDeductionRulesRequest) GetApplicableTo() string {
	if x != nil {
		return x.ApplicableTo
	}
	return ""
}

func (x *ListDeductionRulesRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ListDeductionRulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeductionRulesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// DeductionRulesResponse represents a collection of deduction rules
type DeductionRulesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Rules         []*DeductionRuleResponse `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Total         int32                    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductionRulesResponse) Reset() {
	*x = DeductionRulesResponse{}
	mi := &file_deduction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductionRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductionRulesResponse) ProtoMessage() {}

func (x *DeductionRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductionRulesResponse.ProtoReflect.Descriptor instead.
func (*DeductionRulesResponse) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{4}
}

func (x *DeductionRulesResponse) GetRules() []*DeductionRuleResponse {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *DeductionRulesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ApplyDeductionsRequest represents a request to apply deductions to a stipend
type ApplyDeductionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StudentId        string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StipendId        string                 `protobuf:"bytes,2,opt,name=stipend_id,json=stipendId,proto3" json:"stipend_id,omitempty"`
	StipendType      string                 `protobuf:"bytes,3,opt,name=stipend_type,json=stipendType,proto3" json:"stipend_type,omitempty"`
	BaseAmount       float64                `protobuf:"fixed64,4,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	DeductionRuleIds []string               `protobuf:"bytes,5,rep,name=deduction_rule_ids,json=deductionRuleIds,proto3" json:"deduction_rule_ids,omitempty"` // Optional: specific rules to apply
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyDeductionsRequest) Reset() {
	*x = ApplyDeductionsRequest{}
	mi := &file_deduction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDeductionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDeductionsRequest) ProtoMessage() {}

func (x *ApplyDeductionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDeductionsRequest.ProtoReflect.Descriptor instead.
func (*ApplyDeductionsRequest) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyDeductionsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ApplyDeductionsRequest) GetStipendId() string {
	if x != nil {
		return x.StipendId
	}
	return ""
}

func (x *ApplyDeductionsRequest) GetStipendType() string {
	if x != nil {
		return x.StipendType
	}
	return ""
}

func (x *ApplyDeductionsRequest) GetBaseAmount() float64 {
	if x != nil {
		return x.BaseAmount
	}
	return 0
}

func (x *ApplyDeductionsRequest) GetDeductionRuleIds() []string {
	if x != nil {
		return x.DeductionRuleIds
	}
	return nil
}

// CreateDeductionRequest represents a request to create a deduction
type CreateDeductionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentId       string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	DeductionRuleId string                 `protobuf:"bytes,2,opt,name=deduction_rule_id,json=deductionRuleId,proto3" json:"deduction_rule_id,omitempty"`
	StipendId       string                 `protobuf:"bytes,3,opt,name=stipend_id,json=stipendId,proto3" json:"stipend_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	DeductionType   string                 `protobuf:"bytes,5,opt,name=deduction_type,json=deductionType,proto3" json:"deduction_type,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDeductionRequest) Reset() {
	*x = CreateDeductionRequest{}
	mi := &file_deduction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeductionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeductionRequest) ProtoMessage() {}

func (x *CreateDeductionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeductionRequest.ProtoReflect.Descriptor instead.
func (*CreateDeductionRequest) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDeductionRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateDeductionRequest) GetDeductionRuleId() string {
	if x != nil {
		return x.DeductionRuleId
	}
	return ""
}

func (x *CreateDeductionRequest) GetStipendId() string {
	if x != nil {
		return x.StipendId
	}
	return ""
}

func (x *CreateDeductionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateDeductionRequest) GetDeductionType() string {
	if x != nil {
		return x.DeductionType
	}
	return ""
}

func (x *CreateDeductionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// DeductionResponse represents a deduction
type DeductionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId        string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	DeductionRuleId  string                 `protobuf:"bytes,3,opt,name=deduction_rule_id,json=deductionRuleId,proto3" json:"deduction_rule_id,omitempty"`
	StipendId        string                 `protobuf:"bytes,4,opt,name=stipend_id,json=stipendId,proto3" json:"stipend_id,omitempty"`
	Amount           float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	DeductionType    string                 `protobuf:"bytes,6,opt,name=deduction_type,json=deductionType,proto3" json:"deduction_type,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	DeductionDate    int64                  `protobuf:"varint,8,opt,name=deduction_date,json=deductionDate,proto3" json:"deduction_date,omitempty"` // Unix timestamp
	ProcessingStatus string                 `protobuf:"bytes,9,opt,name=processing_status,json=processingStatus,proto3" json:"processing_status,omitempty"`
	ApprovedBy       string                 `protobuf:"bytes,10,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`        // UUID
	ApprovalDate     int64                  `protobuf:"varint,11,opt,name=approval_date,json=approvalDate,proto3" json:"approval_date,omitempty"` // Unix timestamp
	RejectionReason  string                 `protobuf:"bytes,12,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	TransactionId    string                 `protobuf:"bytes,13,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // Unix timestamp
	ModifiedAt       int64                  `protobuf:"varint,15,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"` // Unix timestamp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeductionResponse) Reset() {
	*x = DeductionResponse{}
	mi := &file_deduction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductionResponse) ProtoMessage() {}

func (x *DeductionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductionResponse.ProtoReflect.Descriptor instead.
func (*DeductionResponse) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{7}
}

func (x *DeductionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeductionResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *DeductionResponse) GetDeductionRuleId() string {
	if x != nil {
		return x.DeductionRuleId
	}
	return ""
}

func (x *DeductionResponse) GetStipendId() string {
	if x != nil {
		return x.StipendId
	}
	return ""
}

func (x *DeductionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DeductionResponse) GetDeductionType() string {
	if x != nil {
		return x.DeductionType
	}
	return ""
}

func (x *DeductionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeductionResponse) GetDeductionDate() int64 {
	if x != nil {
		return x.DeductionDate
	}
	return 0
}

func (x *DeductionResponse) GetProcessingStatus() string {
	if x != nil {
		return x.ProcessingStatus
	}
	return ""
}

func (x *DeductionResponse) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *DeductionResponse) GetApprovalDate() int64 {
	if x != nil {
		return x.ApprovalDate
	}
	return 0
}

func (x *DeductionResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *DeductionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DeductionResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DeductionResponse) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

// GetDeductionRequest represents a request to get a deduction
type GetDeductionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeductionId   string                 `protobuf:"bytes,1,opt,name=deduction_id,json=deductionId,proto3" json:"deduction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeductionRequest) Reset() {
	*x = GetDeductionRequest{}
	mi := &file_deduction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeductionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeductionRequest) ProtoMessage() {}

func (x *GetDeductionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeductionRequest.ProtoReflect.Descriptor instead.
func (*GetDeductionRequest) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeductionRequest) GetDeductionId() string {
	if x != nil {
		return x.DeductionId
	}
	return ""
}

// GetStipendDeductionsRequest represents a request to get deductions for a stipend
type GetStipendDeductionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StipendId     string                 `protobuf:"bytes,1,opt,name=stipend_id,json=stipendId,proto3" json:"stipend_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStipendDeductionsRequest) Reset() {
	*x = GetStipendDeductionsRequest{}
	mi := &file_deduction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStipendDeductionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStipendDeductionsRequest) ProtoMessage() {}

func (x *GetStipendDeductionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStipendDeductionsRequest.ProtoReflect.Descriptor instead.
func (*GetStipendDeductionsRequest) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{9}
}

func (x *GetStipendDeductionsRequest) GetStipendId() string {
	if x != nil {
		return x.StipendId
	}
	return ""
}

func (x *GetStipendDeductionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStipendDeductionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetStudentDeductionsRequest represents a request to get deductions for a student
type GetStudentDeductionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentDeductionsRequest) Reset() {
	*x = GetStudentDeductionsRequest{}
	mi := &file_deduction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentDeductionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentDeductionsRequest) ProtoMessage() {}

func (x *GetStudentDeductionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentDeductionsRequest.ProtoReflect.Descriptor instead.
func (*GetStudentDeductionsRequest) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{10}
}

func (x *GetStudentDeductionsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetStudentDeductionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStudentDeductionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// DeductionsResponse represents a collection of deductions
type DeductionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deductions    []*DeductionResponse   `protobuf:"bytes,1,rep,name=deductions,proto3" json:"deductions,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductionsResponse) Reset() {
	*x = DeductionsResponse{}
	mi := &file_deduction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductionsResponse) ProtoMessage() {}

func (x *DeductionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deduction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductionsResponse.ProtoReflect.Descriptor instead.
func (*DeductionsResponse) Descriptor() ([]byte, []int) {
	return file_deduction_proto_rawDescGZIP(), []int{11}
}

func (x *DeductionsResponse) GetDeductions() []*DeductionResponse {
	if x != nil {
		return x.Deductions
	}
	return nil
}

func (x *DeductionsResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *DeductionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_deduction_proto protoreflect.FileDescriptor

const file_deduction_proto_rawDesc = "" +
	"\n" +
	"\x0fdeduction.proto\x12\x02pb\"\xe9\x02\n" +
	"\x1aCreateDeductionRuleRequest\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12%\n" +
	"\x0ededuction_type\x18\x02 \x01(\tR\rdeductionType\x12%\n" +
	"\x0edefault_amount\x18\x03 \x01(\x01R\rdefaultAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x05 \x01(\x01R\tmaxAmount\x12\x1c\n" +
	"\tfrequency\x18\x06 \x01(\tR\tfrequency\x12!\n" +
	"\fis_mandatory\x18\a \x01(\bR\visMandatory\x12#\n" +
	"\rapplicable_to\x18\b \x01(\tR\fapplicableTo\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"\xd1\x03\n" +
	"\x15DeductionRuleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12%\n" +
	"\x0ededuction_type\x18\x03 \x01(\tR\rdeductionType\x12%\n" +
	"\x0edefault_amount\x18\x04 \x01(\x01R\rdefaultAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x06 \x01(\x01R\tmaxAmount\x12\x1c\n" +
	"\tfrequency\x18\a \x01(\tR\tfrequency\x12!\n" +
	"\fis_mandatory\x18\b \x01(\bR\visMandatory\x12#\n" +
	"\rapplicable_to\x18\t \x01(\tR\fapplicableTo\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\x0e \x01(\x03R\n" +
	"modifiedAt\"2\n" +
	"\x17GetDeductionRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"\x8b\x01\n" +
	"\x19ListDeductionRulesRequest\x12#\n" +
	"\rapplicable_to\x18\x01 \x01(\tR\fapplicableTo\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"_\n" +
	"\x16DeductionRulesResponse\x12/\n" +
	"\x05rules\x18\x01 \x03(\v2\x19.pb.DeductionRuleResponseR\x05rules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc8\x01\n" +
	"\x16ApplyDeductionsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"stipend_id\x18\x02 \x01(\tR\tstipendId\x12!\n" +
	"\fstipend_type\x18\x03 \x01(\tR\vstipendType\x12\x1f\n" +
	"\vbase_amount\x18\x04 \x01(\x01R\n" +
	"baseAmount\x12,\n" +
	"\x12deduction_rule_ids\x18\x05 \x03(\tR\x10deductionRuleIds\"\xe3\x01\n" +
	"\x16CreateDeductionRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12*\n" +
	"\x11deduction_rule_id\x18\x02 \x01(\tR\x0fdeductionRuleId\x12\x1d\n" +
	"\n" +
	"stipend_id\x18\x03 \x01(\tR\tstipendId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12%\n" +
	"\x0ededuction_type\x18\x05 \x01(\tR\rdeductionType\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\x9a\x04\n" +
	"\x11DeductionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12*\n" +
	"\x11deduction_rule_id\x18\x03 \x01(\tR\x0fdeductionRuleId\x12\x1d\n" +
	"\n" +
	"stipend_id\x18\x04 \x01(\tR\tstipendId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12%\n" +
	"\x0ededuction_type\x18\x06 \x01(\tR\rdeductionType\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12%\n" +
	"\x0ededuction_date\x18\b \x01(\x03R\rdeductionDate\x12+\n" +
	"\x11processing_status\x18\t \x01(\tR\x10processingStatus\x12\x1f\n" +
	"\vapproved_by\x18\n" +
	" \x01(\tR\n" +
	"approvedBy\x12#\n" +
	"\rapproval_date\x18\v \x01(\x03R\fapprovalDate\x12)\n" +
	"\x10rejection_reason\x18\f \x01(\tR\x0frejectionReason\x12%\n" +
	"\x0etransaction_id\x18\r \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\x0f \x01(\x03R\n" +
	"modifiedAt\"8\n" +
	"\x13GetDeductionRequest\x12!\n" +
	"\fdeduction_id\x18\x01 \x01(\tR\vdeductionId\"j\n" +
	"\x1bGetStipendDeductionsRequest\x12\x1d\n" +
	"\n" +
	"stipend_id\x18\x01 \x01(\tR\tstipendId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"j\n" +
	"\x1bGetStudentDeductionsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x84\x01\n" +
	"\x12DeductionsResponse\x125\n" +
	"\n" +
	"deductions\x18\x01 \x03(\v2\x15.pb.DeductionResponseR\n" +
	"deductions\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total*\x8b\x01\n" +
	"\x11DeductionRuleType\x12#\n" +
	"\x1fDEDUCTION_RULE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06HOSTEL\x10\x01\x12\x0f\n" +
	"\vELECTRICITY\x10\x02\x12\r\n" +
	"\tMESS_FEES\x10\x03\x12\t\n" +
	"\x05WATER\x10\x04\x12\x0f\n" +
	"\vMAINTENANCE\x10\x05\x12\t\n" +
	"\x05OTHER\x10\x06*p\n" +
	"\x15ApplicableStudentType\x12'\n" +
	"#APPLICABLE_STUDENT_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ALL\x10\x01\x12\x14\n" +
	"\x10FULL_SCHOLARSHIP\x10\x02\x12\x0f\n" +
	"\vSELF_FUNDED\x10\x032\xf0\x04\n" +
	"\x10DeductionService\x12P\n" +
	"\x13CreateDeductionRule\x12\x1e.pb.CreateDeductionRuleRequest\x1a\x19.pb.DeductionRuleResponse\x12J\n" +
	"\x10GetDeductionRule\x12\x1b.pb.GetDeductionRuleRequest\x1a\x19.pb.DeductionRuleResponse\x12O\n" +
	"\x12ListDeductionRules\x12\x1d.pb.ListDeductionRulesRequest\x1a\x1a.pb.DeductionRulesResponse\x12E\n" +
	"\x0fApplyDeductions\x12\x1a.pb.ApplyDeductionsRequest\x1a\x16.pb.DeductionsResponse\x12D\n" +
	"\x0fCreateDeduction\x12\x1a.pb.CreateDeductionRequest\x1a\x15.pb.DeductionResponse\x12>\n" +
	"\fGetDeduction\x12\x17.pb.GetDeductionRequest\x1a\x15.pb.DeductionResponse\x12O\n" +
	"\x14GetStipendDeductions\x12\x1f.pb.GetStipendDeductionsRequest\x1a\x16.pb.DeductionsResponse\x12O\n" +
	"\x14GetStudentDeductions\x12\x1f.pb.GetStudentDeductionsRequest\x1a\x16.pb.DeductionsResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_deduction_proto_rawDescOnce sync.Once
	file_deduction_proto_rawDescData []byte
)

func file_deduction_proto_rawDescGZIP() []byte {
	file_deduction_proto_rawDescOnce.Do(func() {
		file_deduction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deduction_proto_rawDesc), len(file_deduction_proto_rawDesc)))
	})
	return file_deduction_proto_rawDescData
}

var file_deduction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_deduction_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_deduction_proto_goTypes = []any{
	(DeductionRuleType)(0),              // 0: pb.DeductionRuleType
	(ApplicableStudentType)(0),          // 1: pb.ApplicableStudentType
	(*CreateDeductionRuleRequest)(nil),  // 2: pb.CreateDeductionRuleRequest
	(*DeductionRuleResponse)(nil),       // 3: pb.DeductionRuleResponse
	(*GetDeductionRuleRequest)(nil),     // 4: pb.GetDeductionRuleRequest
	(*ListDeductionRulesRequest)(nil),   // 5: pb.ListDeductionRulesRequest
	(*DeductionRulesResponse)(nil),      // 6: pb.DeductionRulesResponse
	(*ApplyDeductionsRequest)(nil),      // 7: pb.ApplyDeductionsRequest
	(*CreateDeductionRequest)(nil),      // 8: pb.CreateDeductionRequest
	(*DeductionResponse)(nil),           // 9: pb.DeductionResponse
	(*GetDeductionRequest)(nil),         // 10: pb.GetDeductionRequest
	(*GetStipendDeductionsRequest)(nil), // 11: pb.GetStipendDeductionsRequest
	(*GetStudentDeductionsRequest)(nil), // 12: pb.GetStudentDeductionsRequest
	(*DeductionsResponse)(nil),          // 13: pb.DeductionsResponse
}
var file_deduction_proto_depIdxs = []int32{
	3,  // 0: pb.DeductionRulesResponse.rules:type_name -> pb.DeductionRuleResponse
	9,  // 1: pb.DeductionsResponse.deductions:type_name -> pb.DeductionResponse
	2,  // 2: pb.DeductionService.CreateDeductionRule:input_type -> pb.CreateDeductionRuleRequest
	4,  // 3: pb.DeductionService.GetDeductionRule:input_type -> pb.GetDeductionRuleRequest
	5,  // 4: pb.DeductionService.ListDeductionRules:input_type -> pb.ListDeductionRulesRequest
	7,  // 5: pb.DeductionService.ApplyDeductions:input_type -> pb.ApplyDeductionsRequest
	8,  // 6: pb.DeductionService.CreateDeduction:input_type -> pb.CreateDeductionRequest
	10, // 7: pb.DeductionService.GetDeduction:input_type -> pb.GetDeductionRequest
	11, // 8: pb.DeductionService.GetStipendDeductions:input_type -> pb.GetStipendDeductionsRequest
	12, // 9: pb.DeductionService.GetStudentDeductions:input_type -> pb.GetStudentDeductionsRequest
	3,  // 10: pb.DeductionService.CreateDeductionRule:output_type -> pb.DeductionRuleResponse
	3,  // 11: pb.DeductionService.GetDeductionRule:output_type -> pb.DeductionRuleResponse
	6,  // 12: pb.DeductionService.ListDeductionRules:output_type -> pb.DeductionRulesResponse
	13, // 13: pb.DeductionService.ApplyDeductions:output_type -> pb.DeductionsResponse
	9,  // 14: pb.DeductionService.CreateDeduction:output_type -> pb.DeductionResponse
	9,  // 15: pb.DeductionService.GetDeduction:output_type -> pb.DeductionResponse
	13, // 16: pb.DeductionService.GetStipendDeductions:output_type -> pb.DeductionsResponse
	13, // 17: pb.DeductionService.GetStudentDeductions:output_type -> pb.DeductionsResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_deduction_proto_init() }
func file_deduction_proto_init() {
	if File_deduction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deduction_proto_rawDesc), len(file_deduction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deduction_proto_goTypes,
		DependencyIndexes: file_deduction_proto_depIdxs,
		EnumInfos:         file_deduction_proto_enumTypes,
		MessageInfos:      file_deduction_proto_msgTypes,
	}.Build()
	File_deduction_proto = out.File
	file_deduction_proto_goTypes = nil
	file_deduction_proto_depIdxs = nil
}
