// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: deduction.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeductionService_CreateDeductionRule_FullMethodName  = "/pb.DeductionService/CreateDeductionRule"
	DeductionService_GetDeductionRule_FullMethodName     = "/pb.DeductionService/GetDeductionRule"
	DeductionService_ListDeductionRules_FullMethodName   = "/pb.DeductionService/ListDeductionRules"
	DeductionService_ApplyDeductions_FullMethodName      = "/pb.DeductionService/ApplyDeductions"
	DeductionService_CreateDeduction_FullMethodName      = "/pb.DeductionService/CreateDeduction"
	DeductionService_GetDeduction_FullMethodName         = "/pb.DeductionService/GetDeduction"
	DeductionService_GetStipendDeductions_FullMethodName = "/pb.DeductionService/GetStipendDeductions"
	DeductionService_GetStudentDeductions_FullMethodName = "/pb.DeductionService/GetStudentDeductions"
)

// DeductionServiceClient is the client API for DeductionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeductionServiceClient interface {
	// CreateDeductionRule creates a new deduction rule
	CreateDeductionRule(ctx context.Context, in *CreateDeductionRuleRequest, opts ...grpc.CallOption) (*DeductionRuleResponse, error)
	// GetDeductionRule retrieves a deduction rule by ID
	GetDeductionRule(ctx context.Context, in *GetDeductionRuleRequest, opts ...grpc.CallOption) (*DeductionRuleResponse, error)
	// ListDeductionRules lists all deduction rules with optional filters
	ListDeductionRules(ctx context.Context, in *ListDeductionRulesRequest, opts ...grpc.CallOption) (*DeductionRulesResponse, error)
	// ApplyDeductions applies deductions to a stipend
	ApplyDeductions(ctx context.Context, in *ApplyDeductionsRequest, opts ...grpc.CallOption) (*DeductionsResponse, error)
	// CreateDeduction creates a new deduction record
	CreateDeduction(ctx context.Context, in *CreateDeductionRequest, opts ...grpc.CallOption) (*DeductionResponse, error)
	// GetDeduction retrieves a deduction by ID
	GetDeduction(ctx context.Context, in *GetDeductionRequest, opts ...grpc.CallOption) (*DeductionResponse, error)
	// GetStipendDeductions retrieves all deductions for a stipend
	GetStipendDeductions(ctx context.Context, in *GetStipendDeductionsRequest, opts ...grpc.CallOption) (*DeductionsResponse, error)
	// GetStudentDeductions retrieves all deductions for a student
	GetStudentDeductions(ctx context.Context, in *GetStudentDeductionsRequest, opts ...grpc.CallOption) (*DeductionsResponse, error)
}

type deductionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeductionServiceClient(cc grpc.ClientConnInterface) DeductionServiceClient {
	return &deductionServiceClient{cc}
}

func (c *deductionServiceClient) CreateDeductionRule(ctx context.Context, in *CreateDeductionRuleRequest, opts ...grpc.CallOption) (*DeductionRuleResponse, error) {
	out := new(DeductionRuleResponse)
	err := c.cc.Invoke(ctx, DeductionService_CreateDeductionRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deductionServiceClient) GetDeductionRule(ctx context.Context, in *GetDeductionRuleRequest, opts ...grpc.CallOption) (*DeductionRuleResponse, error) {
	out := new(DeductionRuleResponse)
	err := c.cc.Invoke(ctx, DeductionService_GetDeductionRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deductionServiceClient) ListDeductionRules(ctx context.Context, in *ListDeductionRulesRequest, opts ...grpc.CallOption) (*DeductionRulesResponse, error) {
	out := new(DeductionRulesResponse)
	err := c.cc.Invoke(ctx, DeductionService_ListDeductionRules_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deductionServiceClient) ApplyDeductions(ctx context.Context, in *ApplyDeductionsRequest, opts ...grpc.CallOption) (*DeductionsResponse, error) {
	out := new(DeductionsResponse)
	err := c.cc.Invoke(ctx, DeductionService_ApplyDeductions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deductionServiceClient) CreateDeduction(ctx context.Context, in *CreateDeductionRequest, opts ...grpc.CallOption) (*DeductionResponse, error) {
	out := new(DeductionResponse)
	err := c.cc.Invoke(ctx, DeductionService_CreateDeduction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deductionServiceClient) GetDeduction(ctx context.Context, in *GetDeductionRequest, opts ...grpc.CallOption) (*DeductionResponse, error) {
	out := new(DeductionResponse)
	err := c.cc.Invoke(ctx, DeductionService_GetDeduction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deductionServiceClient) GetStipendDeductions(ctx context.Context, in *GetStipendDeductionsRequest, opts ...grpc.CallOption) (*DeductionsResponse, error) {
	out := new(DeductionsResponse)
	err := c.cc.Invoke(ctx, DeductionService_GetStipendDeductions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deductionServiceClient) GetStudentDeductions(ctx context.Context, in *GetStudentDeductionsRequest, opts ...grpc.CallOption) (*DeductionsResponse, error) {
	out := new(DeductionsResponse)
	err := c.cc.Invoke(ctx, DeductionService_GetStudentDeductions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeductionServiceServer is the server API for DeductionService service.
// All implementations must embed UnimplementedDeductionServiceServer
// for forward compatibility
type DeductionServiceServer interface {
	// CreateDeductionRule creates a new deduction rule
	CreateDeductionRule(context.Context, *CreateDeductionRuleRequest) (*DeductionRuleResponse, error)
	// GetDeductionRule retrieves a deduction rule by ID
	GetDeductionRule(context.Context, *GetDeductionRuleRequest) (*DeductionRuleResponse, error)
	// ListDeductionRules lists all deduction rules with optional filters
	ListDeductionRules(context.Context, *ListDeductionRulesRequest) (*DeductionRulesResponse, error)
	// ApplyDeductions applies deductions to a stipend
	ApplyDeductions(context.Context, *ApplyDeductionsRequest) (*DeductionsResponse, error)
	// CreateDeduction creates a new deduction record
	CreateDeduction(context.Context, *CreateDeductionRequest) (*DeductionResponse, error)
	// GetDeduction retrieves a deduction by ID
	GetDeduction(context.Context, *GetDeductionRequest) (*DeductionResponse, error)
	// GetStipendDeductions retrieves all deductions for a stipend
	GetStipendDeductions(context.Context, *GetStipendDeductionsRequest) (*DeductionsResponse, error)
	// GetStudentDeductions retrieves all deductions for a student
	GetStudentDeductions(context.Context, *GetStudentDeductionsRequest) (*DeductionsResponse, error)
	mustEmbedUnimplementedDeductionServiceServer()
}

// UnimplementedDeductionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeductionServiceServer struct {
}

func (UnimplementedDeductionServiceServer) CreateDeductionRule(context.Context, *CreateDeductionRuleRequest) (*DeductionRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeductionRule not implemented")
}
func (UnimplementedDeductionServiceServer) GetDeductionRule(context.Context, *GetDeductionRuleRequest) (*DeductionRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeductionRule not implemented")
}
func (UnimplementedDeductionServiceServer) ListDeductionRules(context.Context, *ListDeductionRulesRequest) (*DeductionRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeductionRules not implemented")
}
func (UnimplementedDeductionServiceServer) ApplyDeductions(context.Context, *ApplyDeductionsRequest) (*DeductionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDeductions not implemented")
}
func (UnimplementedDeductionServiceServer) CreateDeduction(context.Context, *CreateDeductionRequest) (*DeductionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeduction not implemented")
}
func (UnimplementedDeductionServiceServer) GetDeduction(context.Context, *GetDeductionRequest) (*DeductionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeduction not implemented")
}
func (UnimplementedDeductionServiceServer) GetStipendDeductions(context.Context, *GetStipendDeductionsRequest) (*DeductionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStipendDeductions not implemented")
}
func (UnimplementedDeductionServiceServer) GetStudentDeductions(context.Context, *GetStudentDeductionsRequest) (*DeductionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentDeductions not implemented")
}
func (UnimplementedDeductionServiceServer) mustEmbedUnimplementedDeductionServiceServer() {}

// UnsafeDeductionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeductionServiceServer will
// result in compilation errors.
type UnsafeDeductionServiceServer interface {
	mustEmbedUnimplementedDeductionServiceServer()
}

func RegisterDeductionServiceServer(s grpc.ServiceRegistrar, srv DeductionServiceServer) {
	s.RegisterService(&DeductionService_ServiceDesc, srv)
}

func _DeductionService_CreateDeductionRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeductionRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).CreateDeductionRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_CreateDeductionRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).CreateDeductionRule(ctx, req.(*CreateDeductionRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeductionService_GetDeductionRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeductionRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).GetDeductionRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_GetDeductionRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).GetDeductionRule(ctx, req.(*GetDeductionRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeductionService_ListDeductionRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeductionRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).ListDeductionRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_ListDeductionRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).ListDeductionRules(ctx, req.(*ListDeductionRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeductionService_ApplyDeductions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDeductionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).ApplyDeductions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_ApplyDeductions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).ApplyDeductions(ctx, req.(*ApplyDeductionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeductionService_CreateDeduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).CreateDeduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_CreateDeduction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).CreateDeduction(ctx, req.(*CreateDeductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeductionService_GetDeduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).GetDeduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_GetDeduction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).GetDeduction(ctx, req.(*GetDeductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeductionService_GetStipendDeductions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStipendDeductionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).GetStipendDeductions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_GetStipendDeductions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).GetStipendDeductions(ctx, req.(*GetStipendDeductionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeductionService_GetStudentDeductions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentDeductionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).GetStudentDeductions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_GetStudentDeductions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).GetStudentDeductions(ctx, req.(*GetStudentDeductionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeductionService_ServiceDesc is the grpc.ServiceDesc for DeductionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeductionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DeductionService",
	HandlerType: (*DeductionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeductionRule",
			Handler:    _DeductionService_CreateDeductionRule_Handler,
		},
		{
			MethodName: "GetDeductionRule",
			Handler:    _DeductionService_GetDeductionRule_Handler,
		},
		{
			MethodName: "ListDeductionRules",
			Handler:    _DeductionService_ListDeductionRules_Handler,
		},
		{
			MethodName: "ApplyDeductions",
			Handler:    _DeductionService_ApplyDeductions_Handler,
		},
		{
			MethodName: "CreateDeduction",
			Handler:    _DeductionService_CreateDeduction_Handler,
		},
		{
			MethodName: "GetDeduction",
			Handler:    _DeductionService_GetDeduction_Handler,
		},
		{
			MethodName: "GetStipendDeductions",
			Handler:    _DeductionService_GetStipendDeductions_Handler,
		},
		{
			MethodName: "GetStudentDeductions",
			Handler:    _DeductionService_GetStudentDeductions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deduction.proto",
}
