// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: stipend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CalculateStipendRequest represents a request to calculate stipend with deductions
type CalculateStipendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StipendType   string                 `protobuf:"bytes,2,opt,name=stipend_type,json=stipendType,proto3" json:"stipend_type,omitempty"` // "full-scholarship" or "self-funded"
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	JournalNumber string                 `protobuf:"bytes,5,opt,name=journal_number,json=journalNumber,proto3" json:"journal_number,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateStipendRequest) Reset() {
	*x = CalculateStipendRequest{}
	mi := &file_stipend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStipendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStipendRequest) ProtoMessage() {}

func (x *CalculateStipendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStipendRequest.ProtoReflect.Descriptor instead.
func (*CalculateStipendRequest) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateStipendRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CalculateStipendRequest) GetStipendType() string {
	if x != nil {
		return x.StipendType
	}
	return ""
}

func (x *CalculateStipendRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalculateStipendRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CalculateStipendRequest) GetJournalNumber() string {
	if x != nil {
		return x.JournalNumber
	}
	return ""
}

func (x *CalculateStipendRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// CalculateMonthlyStipendRequest represents a request to calculate monthly stipend
type CalculateMonthlyStipendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StipendType   string                 `protobuf:"bytes,2,opt,name=stipend_type,json=stipendType,proto3" json:"stipend_type,omitempty"`
	AnnualAmount  float64                `protobuf:"fixed64,3,opt,name=annual_amount,json=annualAmount,proto3" json:"annual_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateMonthlyStipendRequest) Reset() {
	*x = CalculateMonthlyStipendRequest{}
	mi := &file_stipend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateMonthlyStipendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMonthlyStipendRequest) ProtoMessage() {}

func (x *CalculateMonthlyStipendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMonthlyStipendRequest.ProtoReflect.Descriptor instead.
func (*CalculateMonthlyStipendRequest) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateMonthlyStipendRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CalculateMonthlyStipendRequest) GetStipendType() string {
	if x != nil {
		return x.StipendType
	}
	return ""
}

func (x *CalculateMonthlyStipendRequest) GetAnnualAmount() float64 {
	if x != nil {
		return x.AnnualAmount
	}
	return 0
}

// CalculateAnnualStipendRequest represents a request to calculate annual stipend
type CalculateAnnualStipendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StipendType   string                 `protobuf:"bytes,2,opt,name=stipend_type,json=stipendType,proto3" json:"stipend_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateAnnualStipendRequest) Reset() {
	*x = CalculateAnnualStipendRequest{}
	mi := &file_stipend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateAnnualStipendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAnnualStipendRequest) ProtoMessage() {}

func (x *CalculateAnnualStipendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAnnualStipendRequest.ProtoReflect.Descriptor instead.
func (*CalculateAnnualStipendRequest) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateAnnualStipendRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CalculateAnnualStipendRequest) GetStipendType() string {
	if x != nil {
		return x.StipendType
	}
	return ""
}

func (x *CalculateAnnualStipendRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// DeductionDetail represents a single deduction in the calculation
type DeductionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	DeductionType string                 `protobuf:"bytes,3,opt,name=deduction_type,json=deductionType,proto3" json:"deduction_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IsOptional    bool                   `protobuf:"varint,6,opt,name=is_optional,json=isOptional,proto3" json:"is_optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductionDetail) Reset() {
	*x = DeductionDetail{}
	mi := &file_stipend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductionDetail) ProtoMessage() {}

func (x *DeductionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductionDetail.ProtoReflect.Descriptor instead.
func (*DeductionDetail) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{3}
}

func (x *DeductionDetail) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *DeductionDetail) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *DeductionDetail) GetDeductionType() string {
	if x != nil {
		return x.DeductionType
	}
	return ""
}

func (x *DeductionDetail) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DeductionDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeductionDetail) GetIsOptional() bool {
	if x != nil {
		return x.IsOptional
	}
	return false
}

// CalculationResponse represents the result of a stipend calculation
type CalculationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaseStipendAmount float64                `protobuf:"fixed64,1,opt,name=base_stipend_amount,json=baseStipendAmount,proto3" json:"base_stipend_amount,omitempty"`
	TotalDeductions   float64                `protobuf:"fixed64,2,opt,name=total_deductions,json=totalDeductions,proto3" json:"total_deductions,omitempty"`
	NetStipendAmount  float64                `protobuf:"fixed64,3,opt,name=net_stipend_amount,json=netStipendAmount,proto3" json:"net_stipend_amount,omitempty"`
	Deductions        []*DeductionDetail     `protobuf:"bytes,4,rep,name=deductions,proto3" json:"deductions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculationResponse) Reset() {
	*x = CalculationResponse{}
	mi := &file_stipend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponse) ProtoMessage() {}

func (x *CalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponse.ProtoReflect.Descriptor instead.
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{4}
}

func (x *CalculationResponse) GetBaseStipendAmount() float64 {
	if x != nil {
		return x.BaseStipendAmount
	}
	return 0
}

func (x *CalculationResponse) GetTotalDeductions() float64 {
	if x != nil {
		return x.TotalDeductions
	}
	return 0
}

func (x *CalculationResponse) GetNetStipendAmount() float64 {
	if x != nil {
		return x.NetStipendAmount
	}
	return 0
}

func (x *CalculationResponse) GetDeductions() []*DeductionDetail {
	if x != nil {
		return x.Deductions
	}
	return nil
}

// CreateStipendRequest represents a request to create a stipend
type CreateStipendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StipendType   string                 `protobuf:"bytes,2,opt,name=stipend_type,json=stipendType,proto3" json:"stipend_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	JournalNumber string                 `protobuf:"bytes,5,opt,name=journal_number,json=journalNumber,proto3" json:"journal_number,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStipendRequest) Reset() {
	*x = CreateStipendRequest{}
	mi := &file_stipend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStipendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStipendRequest) ProtoMessage() {}

func (x *CreateStipendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStipendRequest.ProtoReflect.Descriptor instead.
func (*CreateStipendRequest) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{5}
}

func (x *CreateStipendRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateStipendRequest) GetStipendType() string {
	if x != nil {
		return x.StipendType
	}
	return ""
}

func (x *CreateStipendRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateStipendRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateStipendRequest) GetJournalNumber() string {
	if x != nil {
		return x.JournalNumber
	}
	return ""
}

func (x *CreateStipendRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// StipendResponse represents a stipend
type StipendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	StipendType   string                 `protobuf:"bytes,4,opt,name=stipend_type,json=stipendType,proto3" json:"stipend_type,omitempty"`
	PaymentDate   int64                  `protobuf:"varint,5,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"` // Unix timestamp
	PaymentStatus string                 `protobuf:"bytes,6,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	JournalNumber string                 `protobuf:"bytes,8,opt,name=journal_number,json=journalNumber,proto3" json:"journal_number,omitempty"`
	Notes         string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // Unix timestamp
	ModifiedAt    int64                  `protobuf:"varint,11,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StipendResponse) Reset() {
	*x = StipendResponse{}
	mi := &file_stipend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StipendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StipendResponse) ProtoMessage() {}

func (x *StipendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StipendResponse.ProtoReflect.Descriptor instead.
func (*StipendResponse) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{6}
}

func (x *StipendResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StipendResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StipendResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StipendResponse) GetStipendType() string {
	if x != nil {
		return x.StipendType
	}
	return ""
}

func (x *StipendResponse) GetPaymentDate() int64 {
	if x != nil {
		return x.PaymentDate
	}
	return 0
}

func (x *StipendResponse) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *StipendResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *StipendResponse) GetJournalNumber() string {
	if x != nil {
		return x.JournalNumber
	}
	return ""
}

func (x *StipendResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StipendResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StipendResponse) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

// GetStipendRequest represents a request to get a stipend
type GetStipendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StipendId     string                 `protobuf:"bytes,1,opt,name=stipend_id,json=stipendId,proto3" json:"stipend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStipendRequest) Reset() {
	*x = GetStipendRequest{}
	mi := &file_stipend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStipendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStipendRequest) ProtoMessage() {}

func (x *GetStipendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStipendRequest.ProtoReflect.Descriptor instead.
func (*GetStipendRequest) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{7}
}

func (x *GetStipendRequest) GetStipendId() string {
	if x != nil {
		return x.StipendId
	}
	return ""
}

// GetStudentStipendsRequest represents a request to get all stipends for a student
type GetStudentStipendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentStipendsRequest) Reset() {
	*x = GetStudentStipendsRequest{}
	mi := &file_stipend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentStipendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentStipendsRequest) ProtoMessage() {}

func (x *GetStudentStipendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentStipendsRequest.ProtoReflect.Descriptor instead.
func (*GetStudentStipendsRequest) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{8}
}

func (x *GetStudentStipendsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetStudentStipendsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStudentStipendsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// StudentStipendsResponse represents a collection of stipends for a student
type StudentStipendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stipends      []*StipendResponse     `protobuf:"bytes,1,rep,name=stipends,proto3" json:"stipends,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentStipendsResponse) Reset() {
	*x = StudentStipendsResponse{}
	mi := &file_stipend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentStipendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentStipendsResponse) ProtoMessage() {}

func (x *StudentStipendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentStipendsResponse.ProtoReflect.Descriptor instead.
func (*StudentStipendsResponse) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{9}
}

func (x *StudentStipendsResponse) GetStipends() []*StipendResponse {
	if x != nil {
		return x.Stipends
	}
	return nil
}

func (x *StudentStipendsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateStipendPaymentStatusRequest represents a request to update payment status
type UpdateStipendPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StipendId     string                 `protobuf:"bytes,1,opt,name=stipend_id,json=stipendId,proto3" json:"stipend_id,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"` // "Pending", "Processed", "Failed"
	PaymentDate   string                 `protobuf:"bytes,3,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`       // ISO8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStipendPaymentStatusRequest) Reset() {
	*x = UpdateStipendPaymentStatusRequest{}
	mi := &file_stipend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStipendPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStipendPaymentStatusRequest) ProtoMessage() {}

func (x *UpdateStipendPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stipend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStipendPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStipendPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_stipend_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStipendPaymentStatusRequest) GetStipendId() string {
	if x != nil {
		return x.StipendId
	}
	return ""
}

func (x *UpdateStipendPaymentStatusRequest) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *UpdateStipendPaymentStatusRequest) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

var File_stipend_proto protoreflect.FileDescriptor

const file_stipend_proto_rawDesc = "" +
	"\n" +
	"\rstipend.proto\x12\x02pb\"\xd7\x01\n" +
	"\x17CalculateStipendRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstipend_type\x18\x02 \x01(\tR\vstipendType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12%\n" +
	"\x0ejournal_number\x18\x05 \x01(\tR\rjournalNumber\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"\x87\x01\n" +
	"\x1eCalculateMonthlyStipendRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstipend_type\x18\x02 \x01(\tR\vstipendType\x12#\n" +
	"\rannual_amount\x18\x03 \x01(\x01R\fannualAmount\"y\n" +
	"\x1dCalculateAnnualStipendRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstipend_type\x18\x02 \x01(\tR\vstipendType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\xc9\x01\n" +
	"\x0fDeductionDetail\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12%\n" +
	"\x0ededuction_type\x18\x03 \x01(\tR\rdeductionType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\vis_optional\x18\x06 \x01(\bR\n" +
	"isOptional\"\xd3\x01\n" +
	"\x13CalculationResponse\x12.\n" +
	"\x13base_stipend_amount\x18\x01 \x01(\x01R\x11baseStipendAmount\x12)\n" +
	"\x10total_deductions\x18\x02 \x01(\x01R\x0ftotalDeductions\x12,\n" +
	"\x12net_stipend_amount\x18\x03 \x01(\x01R\x10netStipendAmount\x123\n" +
	"\n" +
	"deductions\x18\x04 \x03(\v2\x13.pb.DeductionDetailR\n" +
	"deductions\"\xd4\x01\n" +
	"\x14CreateStipendRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstipend_type\x18\x02 \x01(\tR\vstipendType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12%\n" +
	"\x0ejournal_number\x18\x05 \x01(\tR\rjournalNumber\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"\xe9\x02\n" +
	"\x0fStipendResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12!\n" +
	"\fstipend_type\x18\x04 \x01(\tR\vstipendType\x12!\n" +
	"\fpayment_date\x18\x05 \x01(\x03R\vpaymentDate\x12%\n" +
	"\x0epayment_status\x18\x06 \x01(\tR\rpaymentStatus\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\x12%\n" +
	"\x0ejournal_number\x18\b \x01(\tR\rjournalNumber\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\v \x01(\x03R\n" +
	"modifiedAt\"2\n" +
	"\x11GetStipendRequest\x12\x1d\n" +
	"\n" +
	"stipend_id\x18\x01 \x01(\tR\tstipendId\"h\n" +
	"\x19GetStudentStipendsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"`\n" +
	"\x17StudentStipendsResponse\x12/\n" +
	"\bstipends\x18\x01 \x03(\v2\x13.pb.StipendResponseR\bstipends\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8c\x01\n" +
	"!UpdateStipendPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"stipend_id\x18\x01 \x01(\tR\tstipendId\x12%\n" +
	"\x0epayment_status\x18\x02 \x01(\tR\rpaymentStatus\x12!\n" +
	"\fpayment_date\x18\x03 \x01(\tR\vpaymentDate2\xbc\x04\n" +
	"\x0eStipendService\x12V\n" +
	"\x1eCalculateStipendWithDeductions\x12\x1b.pb.CalculateStipendRequest\x1a\x17.pb.CalculationResponse\x12V\n" +
	"\x17CalculateMonthlyStipend\x12\".pb.CalculateMonthlyStipendRequest\x1a\x17.pb.CalculationResponse\x12T\n" +
	"\x16CalculateAnnualStipend\x12!.pb.CalculateAnnualStipendRequest\x1a\x17.pb.CalculationResponse\x12>\n" +
	"\rCreateStipend\x12\x18.pb.CreateStipendRequest\x1a\x13.pb.StipendResponse\x128\n" +
	"\n" +
	"GetStipend\x12\x15.pb.GetStipendRequest\x1a\x13.pb.StipendResponse\x12P\n" +
	"\x12GetStudentStipends\x12\x1d.pb.GetStudentStipendsRequest\x1a\x1b.pb.StudentStipendsResponse\x12X\n" +
	"\x1aUpdateStipendPaymentStatus\x12%.pb.UpdateStipendPaymentStatusRequest\x1a\x13.pb.StipendResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_stipend_proto_rawDescOnce sync.Once
	file_stipend_proto_rawDescData []byte
)

func file_stipend_proto_rawDescGZIP() []byte {
	file_stipend_proto_rawDescOnce.Do(func() {
		file_stipend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stipend_proto_rawDesc), len(file_stipend_proto_rawDesc)))
	})
	return file_stipend_proto_rawDescData
}

var file_stipend_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_stipend_proto_goTypes = []any{
	(*CalculateStipendRequest)(nil),           // 0: pb.CalculateStipendRequest
	(*CalculateMonthlyStipendRequest)(nil),    // 1: pb.CalculateMonthlyStipendRequest
	(*CalculateAnnualStipendRequest)(nil),     // 2: pb.CalculateAnnualStipendRequest
	(*DeductionDetail)(nil),                   // 3: pb.DeductionDetail
	(*CalculationResponse)(nil),               // 4: pb.CalculationResponse
	(*CreateStipendRequest)(nil),              // 5: pb.CreateStipendRequest
	(*StipendResponse)(nil),                   // 6: pb.StipendResponse
	(*GetStipendRequest)(nil),                 // 7: pb.GetStipendRequest
	(*GetStudentStipendsRequest)(nil),         // 8: pb.GetStudentStipendsRequest
	(*StudentStipendsResponse)(nil),           // 9: pb.StudentStipendsResponse
	(*UpdateStipendPaymentStatusRequest)(nil), // 10: pb.UpdateStipendPaymentStatusRequest
}
var file_stipend_proto_depIdxs = []int32{
	3,  // 0: pb.CalculationResponse.deductions:type_name -> pb.DeductionDetail
	6,  // 1: pb.StudentStipendsResponse.stipends:type_name -> pb.StipendResponse
	0,  // 2: pb.StipendService.CalculateStipendWithDeductions:input_type -> pb.CalculateStipendRequest
	1,  // 3: pb.StipendService.CalculateMonthlyStipend:input_type -> pb.CalculateMonthlyStipendRequest
	2,  // 4: pb.StipendService.CalculateAnnualStipend:input_type -> pb.CalculateAnnualStipendRequest
	5,  // 5: pb.StipendService.CreateStipend:input_type -> pb.CreateStipendRequest
	7,  // 6: pb.StipendService.GetStipend:input_type -> pb.GetStipendRequest
	8,  // 7: pb.StipendService.GetStudentStipends:input_type -> pb.GetStudentStipendsRequest
	10, // 8: pb.StipendService.UpdateStipendPaymentStatus:input_type -> pb.UpdateStipendPaymentStatusRequest
	4,  // 9: pb.StipendService.CalculateStipendWithDeductions:output_type -> pb.CalculationResponse
	4,  // 10: pb.StipendService.CalculateMonthlyStipend:output_type -> pb.CalculationResponse
	4,  // 11: pb.StipendService.CalculateAnnualStipend:output_type -> pb.CalculationResponse
	6,  // 12: pb.StipendService.CreateStipend:output_type -> pb.StipendResponse
	6,  // 13: pb.StipendService.GetStipend:output_type -> pb.StipendResponse
	9,  // 14: pb.StipendService.GetStudentStipends:output_type -> pb.StudentStipendsResponse
	6,  // 15: pb.StipendService.UpdateStipendPaymentStatus:output_type -> pb.StipendResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_stipend_proto_init() }
func file_stipend_proto_init() {
	if File_stipend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stipend_proto_rawDesc), len(file_stipend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stipend_proto_goTypes,
		DependencyIndexes: file_stipend_proto_depIdxs,
		MessageInfos:      file_stipend_proto_msgTypes,
	}.Build()
	File_stipend_proto = out.File
	file_stipend_proto_goTypes = nil
	file_stipend_proto_depIdxs = nil
}
