// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: stipend.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StipendService_CalculateStipendWithDeductions_FullMethodName = "/pb.StipendService/CalculateStipendWithDeductions"
	StipendService_CalculateMonthlyStipend_FullMethodName        = "/pb.StipendService/CalculateMonthlyStipend"
	StipendService_CalculateAnnualStipend_FullMethodName         = "/pb.StipendService/CalculateAnnualStipend"
	StipendService_CreateStipend_FullMethodName                  = "/pb.StipendService/CreateStipend"
	StipendService_GetStipend_FullMethodName                     = "/pb.StipendService/GetStipend"
	StipendService_GetStudentStipends_FullMethodName             = "/pb.StipendService/GetStudentStipends"
	StipendService_UpdateStipendPaymentStatus_FullMethodName     = "/pb.StipendService/UpdateStipendPaymentStatus"
)

// StipendServiceClient is the client API for StipendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StipendServiceClient interface {
	// CalculateStipendWithDeductions calculates stipend amount after applying deductions
	CalculateStipendWithDeductions(ctx context.Context, in *CalculateStipendRequest, opts ...grpc.CallOption) (*CalculationResponse, error)
	// CalculateMonthlyStipend calculates monthly stipend (annual / 12) with deductions
	CalculateMonthlyStipend(ctx context.Context, in *CalculateMonthlyStipendRequest, opts ...grpc.CallOption) (*CalculationResponse, error)
	// CalculateAnnualStipend calculates annual stipend with deductions
	CalculateAnnualStipend(ctx context.Context, in *CalculateAnnualStipendRequest, opts ...grpc.CallOption) (*CalculationResponse, error)
	// CreateStipend creates a new stipend record
	CreateStipend(ctx context.Context, in *CreateStipendRequest, opts ...grpc.CallOption) (*StipendResponse, error)
	// GetStipend retrieves a stipend by ID
	GetStipend(ctx context.Context, in *GetStipendRequest, opts ...grpc.CallOption) (*StipendResponse, error)
	// GetStudentStipends retrieves all stipends for a student
	GetStudentStipends(ctx context.Context, in *GetStudentStipendsRequest, opts ...grpc.CallOption) (*StudentStipendsResponse, error)
	// UpdateStipendPaymentStatus updates the payment status of a stipend
	UpdateStipendPaymentStatus(ctx context.Context, in *UpdateStipendPaymentStatusRequest, opts ...grpc.CallOption) (*StipendResponse, error)
}

type stipendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStipendServiceClient(cc grpc.ClientConnInterface) StipendServiceClient {
	return &stipendServiceClient{cc}
}

func (c *stipendServiceClient) CalculateStipendWithDeductions(ctx context.Context, in *CalculateStipendRequest, opts ...grpc.CallOption) (*CalculationResponse, error) {
	out := new(CalculationResponse)
	err := c.cc.Invoke(ctx, StipendService_CalculateStipendWithDeductions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stipendServiceClient) CalculateMonthlyStipend(ctx context.Context, in *CalculateMonthlyStipendRequest, opts ...grpc.CallOption) (*CalculationResponse, error) {
	out := new(CalculationResponse)
	err := c.cc.Invoke(ctx, StipendService_CalculateMonthlyStipend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stipendServiceClient) CalculateAnnualStipend(ctx context.Context, in *CalculateAnnualStipendRequest, opts ...grpc.CallOption) (*CalculationResponse, error) {
	out := new(CalculationResponse)
	err := c.cc.Invoke(ctx, StipendService_CalculateAnnualStipend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stipendServiceClient) CreateStipend(ctx context.Context, in *CreateStipendRequest, opts ...grpc.CallOption) (*StipendResponse, error) {
	out := new(StipendResponse)
	err := c.cc.Invoke(ctx, StipendService_CreateStipend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stipendServiceClient) GetStipend(ctx context.Context, in *GetStipendRequest, opts ...grpc.CallOption) (*StipendResponse, error) {
	out := new(StipendResponse)
	err := c.cc.Invoke(ctx, StipendService_GetStipend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stipendServiceClient) GetStudentStipends(ctx context.Context, in *GetStudentStipendsRequest, opts ...grpc.CallOption) (*StudentStipendsResponse, error) {
	out := new(StudentStipendsResponse)
	err := c.cc.Invoke(ctx, StipendService_GetStudentStipends_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stipendServiceClient) UpdateStipendPaymentStatus(ctx context.Context, in *UpdateStipendPaymentStatusRequest, opts ...grpc.CallOption) (*StipendResponse, error) {
	out := new(StipendResponse)
	err := c.cc.Invoke(ctx, StipendService_UpdateStipendPaymentStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StipendServiceServer is the server API for StipendService service.
// All implementations must embed UnimplementedStipendServiceServer
// for forward compatibility
type StipendServiceServer interface {
	// CalculateStipendWithDeductions calculates stipend amount after applying deductions
	CalculateStipendWithDeductions(context.Context, *CalculateStipendRequest) (*CalculationResponse, error)
	// CalculateMonthlyStipend calculates monthly stipend (annual / 12) with deductions
	CalculateMonthlyStipend(context.Context, *CalculateMonthlyStipendRequest) (*CalculationResponse, error)
	// CalculateAnnualStipend calculates annual stipend with deductions
	CalculateAnnualStipend(context.Context, *CalculateAnnualStipendRequest) (*CalculationResponse, error)
	// CreateStipend creates a new stipend record
	CreateStipend(context.Context, *CreateStipendRequest) (*StipendResponse, error)
	// GetStipend retrieves a stipend by ID
	GetStipend(context.Context, *GetStipendRequest) (*StipendResponse, error)
	// GetStudentStipends retrieves all stipends for a student
	GetStudentStipends(context.Context, *GetStudentStipendsRequest) (*StudentStipendsResponse, error)
	// UpdateStipendPaymentStatus updates the payment status of a stipend
	UpdateStipendPaymentStatus(context.Context, *UpdateStipendPaymentStatusRequest) (*StipendResponse, error)
	mustEmbedUnimplementedStipendServiceServer()
}

// UnimplementedStipendServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStipendServiceServer struct {
}

func (UnimplementedStipendServiceServer) CalculateStipendWithDeductions(context.Context, *CalculateStipendRequest) (*CalculationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateStipendWithDeductions not implemented")
}
func (UnimplementedStipendServiceServer) CalculateMonthlyStipend(context.Context, *CalculateMonthlyStipendRequest) (*CalculationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateMonthlyStipend not implemented")
}
func (UnimplementedStipendServiceServer) CalculateAnnualStipend(context.Context, *CalculateAnnualStipendRequest) (*CalculationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateAnnualStipend not implemented")
}
func (UnimplementedStipendServiceServer) CreateStipend(context.Context, *CreateStipendRequest) (*StipendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStipend not implemented")
}
func (UnimplementedStipendServiceServer) GetStipend(context.Context, *GetStipendRequest) (*StipendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStipend not implemented")
}
func (UnimplementedStipendServiceServer) GetStudentStipends(context.Context, *GetStudentStipendsRequest) (*StudentStipendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentStipends not implemented")
}
func (UnimplementedStipendServiceServer) UpdateStipendPaymentStatus(context.Context, *UpdateStipendPaymentStatusRequest) (*StipendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStipendPaymentStatus not implemented")
}
func (UnimplementedStipendServiceServer) mustEmbedUnimplementedStipendServiceServer() {}

// UnsafeStipendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StipendServiceServer will
// result in compilation errors.
type UnsafeStipendServiceServer interface {
	mustEmbedUnimplementedStipendServiceServer()
}

func RegisterStipendServiceServer(s grpc.ServiceRegistrar, srv StipendServiceServer) {
	s.RegisterService(&StipendService_ServiceDesc, srv)
}

func _StipendService_CalculateStipendWithDeductions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateStipendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StipendServiceServer).CalculateStipendWithDeductions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StipendService_CalculateStipendWithDeductions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StipendServiceServer).CalculateStipendWithDeductions(ctx, req.(*CalculateStipendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StipendService_CalculateMonthlyStipend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateMonthlyStipendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StipendServiceServer).CalculateMonthlyStipend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StipendService_CalculateMonthlyStipend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StipendServiceServer).CalculateMonthlyStipend(ctx, req.(*CalculateMonthlyStipendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StipendService_CalculateAnnualStipend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateAnnualStipendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StipendServiceServer).CalculateAnnualStipend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StipendService_CalculateAnnualStipend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StipendServiceServer).CalculateAnnualStipend(ctx, req.(*CalculateAnnualStipendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StipendService_CreateStipend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStipendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StipendServiceServer).CreateStipend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StipendService_CreateStipend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StipendServiceServer).CreateStipend(ctx, req.(*CreateStipendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StipendService_GetStipend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStipendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StipendServiceServer).GetStipend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StipendService_GetStipend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StipendServiceServer).GetStipend(ctx, req.(*GetStipendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StipendService_GetStudentStipends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentStipendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StipendServiceServer).GetStudentStipends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StipendService_GetStudentStipends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StipendServiceServer).GetStudentStipends(ctx, req.(*GetStudentStipendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StipendService_UpdateStipendPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStipendPaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StipendServiceServer).UpdateStipendPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StipendService_UpdateStipendPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StipendServiceServer).UpdateStipendPaymentStatus(ctx, req.(*UpdateStipendPaymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StipendService_ServiceDesc is the grpc.ServiceDesc for StipendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StipendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StipendService",
	HandlerType: (*StipendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateStipendWithDeductions",
			Handler:    _StipendService_CalculateStipendWithDeductions_Handler,
		},
		{
			MethodName: "CalculateMonthlyStipend",
			Handler:    _StipendService_CalculateMonthlyStipend_Handler,
		},
		{
			MethodName: "CalculateAnnualStipend",
			Handler:    _StipendService_CalculateAnnualStipend_Handler,
		},
		{
			MethodName: "CreateStipend",
			Handler:    _StipendService_CreateStipend_Handler,
		},
		{
			MethodName: "GetStipend",
			Handler:    _StipendService_GetStipend_Handler,
		},
		{
			MethodName: "GetStudentStipends",
			Handler:    _StipendService_GetStudentStipends_Handler,
		},
		{
			MethodName: "UpdateStipendPaymentStatus",
			Handler:    _StipendService_UpdateStipendPaymentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stipend.proto",
}
